---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: 容量ベースのライセンスの課金、消費モデル、価格設定、構成について理解しておきます。 
---
= Cloud Volumes ONTAPの容量ベースのライセンスの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量ベースのライセンスの課金と容量の使用法について理解しておく必要があります。



== 消費モデルまたはライセンス購入オプション

容量ベースのライセンス パッケージは、次の消費モデルまたは購入オプションで利用できます。

* *BYOL*: 自分のライセンスを持ち込みます (BYOL)。  NetAppから購入したライセンスで、任意のクラウド プロバイダーにCloud Volumes ONTAP を展開するために使用できます。
+

NOTE: はBYOLライセンスの購入、延長、および更新を制限しています。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAPの BYOL ライセンスの利用制限"^] 。



ifdef::azure[]

endif::azure[]

* *PAYGO*: 従量課金制 (PAYGO) サブスクリプションは、クラウド プロバイダーのマーケットプレイスからの時間単位のサブスクリプションです。
* *年間*: クラウド プロバイダーのマーケットプレイスからの年間契約。


次の点に注意してください。

* NetApp （BYOL）からライセンスを購入する場合は、クラウドプロバイダーのマーケットプレイスからPAYGOプランに加入する必要があります。NetAppはBYOLライセンスに制限を設けています。BYOLライセンスの有効期限が切れた場合は、クラウドマーケットプレイスのサブスクリプションに切り替えていただく必要があります。
+
ライセンスは常に最初に課金されますが、以下の場合にはマーケットプレイスの時間単位料金で課金されます。

+
** ライセンス容量を超えた場合
** ライセンスの有効期限が切れた場合


* マーケットプレイスから年間契約を結んでいる場合、導入するすべてのCloud Volumes ONTAPシステムに対してその契約料金が課金されます。年間マーケットプレイス契約と BYOL を組み合わせることはできません。
* 中国リージョンでは、BYOL 対応のシングルノードシステムのみがサポートされます。中国リージョンでのデプロイメントは、BYOL ライセンスの制限の対象外となります。




== ライセンスパッケージの変更

展開後に、容量ベースのライセンスを使用するCloud Volumes ONTAPシステムのパッケージを変更できます。たとえば、Essentials パッケージを使用してCloud Volumes ONTAPシステムを導入した場合、ビジネス ニーズの変化に応じて Professional パッケージに変更できます。

link:task-manage-capacity-licenses.html["充電方法の変更方法を学ぶ"] 。

ノードベースのライセンスを容量ベースのライセンスに変換する方法については、以下を参照してください。



== サポートされているストレージタイプとパッケージの課金方法

Cloud Volumes ONTAPでの課金は、パッケージやボリューム タイプなど、さまざまな要素に基づいて行われます。容量ベースのライセンス パッケージは、Cloud Volumes ONTAP 9.7 以降で利用できます。

価格の詳細については、 https://bluexp.netapp.com/pricing/["NetApp Consoleのウェブサイト"^] 。



=== Storage VM

* 追加のデータ サービス ストレージ VM (SVM) には追加のライセンス コストは発生しませんが、データ サービス SVM ごとに 4 TiB の最小容量料金が発生します。
* ディザスタリカバリ SVM は、プロビジョニングされた容量に応じて課金されます。




=== HAペア

HA ペアの場合、ノードにプロビジョニングされた容量に対してのみ課金されます。パートナー ノードに同期的にミラーリングされるデータに対しては料金は発生しません。



=== FlexCloneおよびFlexCacheボリューム

* FlexCloneボリュームで使用される容量に対しては料金は発生しません。
* ソースおよび宛先のFlexCacheボリュームはプライマリ データと見なされ、プロビジョニングされたスペースに応じて課金されます。




=== 読み取り/書き込みボリューム

書き込み可能 (読み取り/書き込み) ボリュームを作成または使用する場合、そのボリュームはプライマリ ボリュームとみなされ、ストレージ VM (SVM) あたりの最小料金に基づいてプロビジョニングされた容量に対して課金されます。例としては、 FlexVol読み取り/書き込みボリューム、 SnapLock監査ボリューム、CIFS/NFS 監査ボリュームなどがあります。ユーザーが作成したすべてのデータ ボリュームは、サブスクリプションとパッケージ タイプごとに課金されます。  SVM ルート ボリュームなど、自動的に作成され、データを保存できないONTAP内部ボリュームは課金されません。



=== エッセンシャルパッケージ

Essentials パッケージでは、デプロイメント タイプ (HA または単一ノード) とボリューム タイプ (プライマリまたはセカンダリ) に基づいて課金されます。価格は、高いものから低いものの順に、_Essentials Primary HA_、_Essentials Primary Single Node_、_Essentials Secondary HA_、_Essentials Secondary Single Node_ となります。あるいは、マーケットプレイス契約を購入するか、プライベート オファーを受け入れる場合、容量料金はどのデプロイメントまたはボリューム タイプでも同じになります。

ライセンスは、Cloud Volumes ONTAPシステム内で作成されたボリューム タイプに基づいて決定されます。

* Essentials シングルノード: 1 つのONTAPノードのみを使用して、 Cloud Volumes ONTAPシステムで作成されたボリュームの読み取り/書き込み。
* Essentials HA: 相互にフェイルオーバーして中断のないデータ アクセスを実現できる 2 つのONTAPノードを使用してボリュームの読み取り/書き込みを行います。
* Essentials セカンダリ シングル ノード: 1 つのONTAPノードのみを使用してCloud Volumes ONTAPシステム上に作成されたデータ保護 (DP) タイプのボリューム (通常は読み取り専用のSnapMirrorまたはSnapVault宛先ボリューム)。
+

NOTE: 読み取り専用/DP ボリュームがプライマリ ボリュームになった場合、コンソールはそれをプライマリ データと見なし、ボリュームが読み取り/書き込みモードであった時間に基づいて課金コストを計算します。ボリュームが再び読み取り専用/DP になると、ボリュームは再びセカンダリ データとして扱われ、コンソール内の最適なライセンスを使用してそれに応じて課金されます。

* Essentials セカンダリ HA: 中断のないデータ アクセスのために相互にフェイルオーバーできる 2 つのONTAPSnapMirrorを使用してCloud Volumes ONTAPシステム上に作成されたデータ保護 (DP) タイプのボリューム (通常はSnapVault専用の SnapMirror または SnapVault 宛先ボリューム)。




== 容量制限

容量ベースのライセンス モデルでは、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートし、階層化された合計容量はクラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。

各クラウド プロバイダーの容量制限については、各プロバイダーのドキュメントを参照してください。

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWSのドキュメント"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["マネージド ディスクに関する Azure ドキュメント"^]そして https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["BLOB ストレージに関する Azure ドキュメント"^]
* https://cloud.google.com/storage/docs/buckets["Google Cloud ドキュメント"^]




== システムの最大数

容量ベースのライセンスでは、 Cloud Volumes ONTAPシステムの最大数は、 NetApp Console組織ごとに 24 に制限されます。_システム_ とは、 Cloud Volumes ONTAP HA ペア、 Cloud Volumes ONTAPシングルノード システム、または作成した追加のストレージ VM です。デフォルトのストレージ VM は制限にカウントされません。この制限はすべてのライセンス モデルに適用されます。

たとえば、次の 3 つのシステムがあるとします。

* 1 つのストレージ VM を備えた単一ノードのCloud Volumes ONTAPシステム (これは、Cloud Volumes ONTAPを展開するときに作成されるデフォルトのストレージ VM です)
+
このシステムは 1 つのシステムとしてカウントされます。

* 2 つのストレージ VM (デフォルトのストレージ VM と、作成した追加のストレージ VM 1 つ) を備えた単一ノードのCloud Volumes ONTAPシステム
+
このシステムは、単一ノード システム用と追加ストレージ VM 用の 1 つの合計 2 つのシステムとしてカウントされます。

* 3 つのストレージ VM (デフォルトのストレージ VM と、作成した 2 つの追加ストレージ VM) を備えたCloud Volumes ONTAP HA ペア
+
このシステムは、HA ペア用に 1 つ、追加のストレージ VM 用に 2 つ、合わせて 3 つのシステムとしてカウントされます。



合計で6つのシステムになります。すると、組織内にさらに 14 個のシステムを追加できる余裕が生まれます。

24 台を超えるシステムが必要な大規模な展開の場合は、アカウント担当者または営業チームにお問い合わせください。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["AWS、Azure、Google Cloud のストレージ制限について学ぶ"^] 。



== 最低料金

少なくとも 1 つのプライマリ (読み取り/書き込み) ボリュームを持つデータ サービス ストレージ VM ごとに、4 TiB の最小料金がかかります。プライマリ ボリュームの合計が 4 TiB 未満の場合、コンソールはそのストレージ VM に 4 TiB の最小料金を適用します。

まだボリュームをプロビジョニングしていない場合は、最低料金は適用されません。

Essentials パッケージの場合、4 TiB の最小容量料金は、セカンダリ (データ保護) ボリュームのみを含むストレージ VM には適用されません。たとえば、1 TiB のセカンダリ データを持つストレージ VM がある場合、その 1 TiB のデータに対してのみ課金されます。プロフェッショナル パッケージ タイプでは、ボリューム タイプに関係なく、4 TiB の最小容量課金が適用されます。



== 請求設定と超過料金

コンソールの *Licenses and subscriptionsション * セクションで課金方法を選択できます。超過は、ライセンス パッケージまたは年間サブスクリプションで指定された容量を超える使用量が発生したときに発生します。

* * NetAppライセンスを最初に取得*: このモデルでは、まずライセンス パッケージ (BYOL) の容量に対して使用量が課金されます。ライセンス容量を超過した場合、年間マーケットプレイス サブスクリプションまたはマーケットプレイスのオンデマンド時間料金 (PAYGO) に基づいて超過料金が請求されます。BYOL ライセンスの有効期限が切れた場合は、クラウド マーケットプレイスを通じて容量ベースのライセンス モデルに移行する必要があります。詳細については、 link:task-convert-node-capacity.html["Cloud Volumes ONTAPノードベースのライセンスを容量ベースのライセンスに変換する"]。
* *マーケットプレイス サブスクリプションのみ*: このモデルでは、使用量はまず年間マーケットプレイス サブスクリプションに対して課金されます。追加の使用量については、マーケットプレイスのオンデマンド時間料金 (PAYGO) で課金されます。未使用のライセンス容量は課金対象から除外されます。


請求設定の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["ライセンスとサブスクリプションの課金設定について"^]。



=== Essentialsライセンスの超過料金の請求方法

NetAppから Essentials ライセンスを購入し (BYOL)、特定の Essentials パッケージのライセンス容量を超えた場合、コンソールはより高価な Essentials ライセンス (使用可能な容量がある場合) に対して超過分を請求します。コンソールは、マーケットプレイスに対して請求する前に、まず支払った利用可能な容量を使用します。  BYOL ライセンスで利用可能な容量がない場合、超過した容量はマーケットプレイスのオンデマンド時間料金 (PAYGO) で課金され、毎月の請求額に加算されます。

同様に、年間マーケットプレイス契約または複数の Essentials パッケージを含むプライベート オファーがあり、使用量が特定のパッケージのデプロイメントとボリューム タイプに対してコミットされた容量を超える場合、コンソールは利用可能な容量に基づいて、より高価な Essentials パッケージに対して超過分を請求します。容量が使い果たされると、残りの超過分はマーケットプレイス オンデマンド (PAYGO) の時間単位料金で課金され、毎月の請求額に加算されます。

Essentialsライセンスの課金については、以下を参照してください。link:concept-licensing-charging.html#essentialscharging["エッセンシャルパッケージ"] 。

ここに例があります。Essentials パッケージの次のライセンスがあるとします。

* 500 TiB のコミット容量を持つ 500 TiB の _Essentials Secondary HA_ ライセンス
* コミットされた容量が100 TiBのみである500 TiBの_Essentials Single Node_ライセンス


セカンダリ ボリュームを持つ HA ペアにさらに 50 TiB がプロビジョニングされます。コンソールは、その 50 TiB を PAYGO に請求する代わりに、_Essentials Single Node_ ライセンスに対して 50 TiB の超過分を請求します。このライセンスの価格は _Essentials Secondary HA_ よりも高額ですが、すでに購入済みのライセンスを使用するため、毎月の請求額に追加費用はかかりません。

*管理 >Licenses and subscriptions*で、_Essentials Single Node_ ライセンスに対して 50 TiB が課金されていることを確認できます。

もう一つの例を挙げます。  Essentials パッケージの次のライセンスがあるとします。

* 500 TiB のコミット容量を持つ 500 TiB の _Essentials Secondary HA_ ライセンス
* コミットされた容量が100 TiBのみである500 TiBの_Essentials Single Node_ライセンス


プライマリ ボリュームを持つ HA ペアにさらに 100 TiB がプロビジョニングされます。購入したライセンスには、_Essentials Primary HA_ コミット容量がありません。  _Essentials Primary HA_ ライセンスの価格は、_Essentials Primary Single Node_ ライセンスと _Essentials Secondary HA_ ライセンスの両方よりも高くなります。

この例では、コンソールは追加の 100 TiB に対してマーケットプレイス レートで超過料金を請求します。超過料金は毎月の請求書に表示されます。
