---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: コンソールは、Cloud Volumes ONTAPストレージの簡素化された高度な管理を提供します。 
---
= Cloud Volumes ONTAPストレージ管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleは、 Cloud Volumes ONTAPストレージの簡素化された高度な管理を提供します。


CAUTION: すべてのディスクとアグリゲートはコンソールから直接作成および削除する必要があります。これらのアクションを別の管理ツールから実行しないでください。そうすると、システムの安定性に影響が及び、将来的にディスクを追加する能力が妨げられ、クラウド プロバイダーの料金が重複して発生する可能性があります。



== ストレージのプロビジョニング

コンソールを使用すると、ディスクを購入し、アグリゲートを管理することで、 Cloud Volumes ONTAPのストレージ プロビジョニングが簡単になります。ボリュームを作成するだけです。必要に応じて、高度な割り当てオプションを使用して、集約を自分でプロビジョニングすることもできます。



=== 簡素化されたプロビジョニング

アグリゲートはボリュームにクラウド ストレージを提供します。インスタンスを起動するとき、および追加のボリュームをプロビジョニングするときに、コンソールによってアグリゲートが作成されます。

ボリュームを作成すると、コンソールは次の 3 つのうちのいずれかを実行します。

* 十分な空き領域がある既存のアグリゲートにボリュームを配置します。
* 既存のアグリゲート用にさらにディスクを購入して、そのアグリゲートにボリュームを配置します。


ifdef::aws[]

+ Elastic Volumes をサポートする AWS のアグリゲートの場合、RAID グループ内のディスクのサイズも増加します。link:concept-aws-elastic-volumes.html["エラスティックボリュームのサポートについて詳しくはこちら"] 。

endif::aws[]

* 新しいアグリゲート用のディスクを購入し、そのアグリゲートにボリュームを配置します。


コンソールは、アグリゲートの最大サイズ、シン プロビジョニングが有効かどうか、アグリゲートの空き領域のしきい値など、いくつかの要素を確認して、新しいボリュームを配置する場所を決定します。

ifdef::aws[]



==== AWS のアグリゲートのディスクサイズの選択

コンソールは、AWS でCloud Volumes ONTAPの新しいアグリゲートを作成すると、アグリゲート数が増加するにつれてディスク サイズを徐々に増やし、AWS データのディスク制限に達する前にシステム容量を最大化します。

たとえば、コンソールは次のディスク サイズを選択する場合があります。

[cols="3*"]
|===
| 合計数 | ディスク サイズ | 最大総容量 


| 1 | 500ギガバイト | 3 TiB 


| 4 | 1 TiB | 6 TiB 


| 6 | 2 TiB | 12 TiB 
|===

NOTE: この動作は、Amazon EBS Elastic Volumes 機能をサポートするアグリゲートには適用されません。エラスティック ボリュームが有効になっているアグリゲートは、1 つまたは 2 つの RAID グループで構成されます。各 RAID グループには、同じ容量を持つ 4 つの同一ディスクがあります。link:concept-aws-elastic-volumes.html["エラスティックボリュームのサポートについて詳しくはこちら"] 。

高度な割り当てオプションを使用して、ディスク サイズを自分で選択できます。

endif::aws[]



=== 高度な割り当て

集計を管理することもできます。link:task-create-aggregates.html["*高度な割り当て*ページから"] 、特定の数のディスクを含む新しいアグリゲートを作成したり、既存のアグリゲートにディスクを追加したり、特定のアグリゲートにボリュームを作成したりできます。



== 容量管理

組織またはアカウント管理者は、ストレージ容量の決定を通知したり、容量要件を自動的に管理するかどうかをコンソールで設定できます。

この動作は、コンソール エージェントの _容量管理モード_ によって決まります。容量管理モードは、そのコンソール エージェントによって管理されるすべてのCloud Volumes ONTAPシステムに影響します。別のコンソール エージェントがある場合は、別の方法で構成できます。



=== 自動容量管理

容量管理モードは、デフォルトで自動に設定されています。このモードでは、コンソールは 15 分ごとに空き領域比率をチェックし、空き領域比率が指定されたしきい値を下回っているかどうかを判断します。さらに容量が必要な場合は、新しいディスクの購入を開始し、使用されていないディスクのコレクション (アグリゲート) を削除し、必要に応じてアグリゲート間でボリュームを移動し、ディスク障害を防止します。

次の例は、このモードがどのように動作するかを示しています。

* アグリゲートが容量しきい値に達し、さらにディスクを追加する余裕がある場合、コンソールはボリュームが引き続き拡張できるように、そのアグリゲート用に新しいディスクを自動的に購入します。
+
ifdef::aws[]



Elastic Volumes をサポートする AWS のアグリゲートの場合、RAID グループ内のディスクのサイズも増加します。link:concept-aws-elastic-volumes.html["エラスティックボリュームのサポートについて詳しくはこちら"] 。

endif::aws[]

+ * アグリゲートが容量しきい値に達し、追加のディスクをサポートできない場合、コンソールはボリュームをそのアグリゲートから使用可能な容量を持つアグリゲートまたは新しいアグリゲートに自動的に移動します。

+ コンソールがボリュームの新しいアグリゲートを作成する場合、そのボリュームのサイズに対応するディスク サイズが選択されます。

+ 元のアグリゲートで空き領域が利用可能になったことに注意してください。既存のボリュームまたは新しいボリュームがそのスペースを使用できます。このシナリオでは、スペースをクラウド プロバイダーに返却することはできません。

* アグリゲートにボリュームが 12 時間以上含まれていない場合、コンソールはそれを削除します。




==== 自動容量管理によるLUNの管理

コンソールの自動容量管理は LUN には適用されません。  LUN を作成すると、自動拡張機能が無効になります。



=== 手動容量管理

組織またはアカウント管理者が *容量管理モード* を手動に設定した場合、コンソールは容量の決定に対して適切なアクションを実行するように通知します。自動モードで説明したのと同じ例が手動モードにも当てはまりますが、アクションを受け入れるかどうかはユーザー次第です。



=== 詳細情報

link:task-manage-capacity-settings.html["容量管理モードを変更する方法を学ぶ"] 。
