---
sidebar: sidebar 
permalink: concept-overview-cvo.html 
keywords: what is cloud volumes ontap, cloud volumes ontap features, features, cloud volumes ontap overview, overview of cloud volumes ontap, cloud backup, cloud data sense 
summary: Cloud Volumes ONTAP を使用すると、データ保護、セキュリティ、コンプライアンスを強化しながら、クラウド ストレージのコストとパフォーマンスを最適化できます。 
---
= Cloud Volumes ONTAPについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP を使用すると、データ保護、セキュリティ、コンプライアンスを強化しながら、クラウド ストレージのコストとパフォーマンスを最適化できます。

Cloud Volumes ONTAPは、クラウドでONTAPデータ管理ソフトウェアを実行するソフトウェアのみのストレージ アプライアンスです。次の主要機能を備えたエンタープライズ グレードのストレージを提供します。

* ストレージ効率
+
組み込みのデータ重複排除、データ圧縮、シン プロビジョニング、クローン作成を活用して、ストレージ コストを最小限に抑えます。

* 高可用性
+
クラウド環境で障害が発生した場合でも、企業の信頼性と継続的な運用を確保します。

* データ保護
+
Cloud Volumes ONTAP は、業界をリードする NetApp のレプリケーション テクノロジーであるSnapMirrorを活用してオンプレミスのデータをクラウドに複製するため、複数のユース ケースで使用できるセカンダリ コピーを簡単に作成できます。

+
Cloud Volumes ONTAP はNetApp Backup and Recoveryとも統合されており、クラウド データの保護と長期アーカイブのためのバックアップおよび復元機能も提供します。

+
link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["バックアップとリカバリの詳細"^]

* データ階層化
+
アプリケーションをオフラインにすることなく、高パフォーマンスと低パフォーマンスのストレージ プールをオンデマンドで切り替えます。

* アプリケーションの一貫性
+
NetApp SnapCenterを使用して、 NetApp Snapshot コピーの一貫性を確保します。

+
https://docs.netapp.com/us-en/snapcenter/get-started/concept_snapcenter_overview.html["SnapCenterについて詳しくはこちら"^]

* Data security
+
Cloud Volumes ONTAP はデータ暗号化をサポートし、ウイルスやランサムウェアからの保護を提供します。

* プライバシーコンプライアンス管理
+
NetApp Data Classificationとの統合により、データのコンテキストを理解し、機密データを識別できるようになります。

+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["データ分類の詳細"^]




NOTE: ONTAP機能のライセンスは、Cloud Volumes ONTAPに含まれています。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["サポートされているCloud Volumes ONTAP構成を表示する"^]

https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAPの詳細"^]
