---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: コンソールは、Cloud Volumes ONTAPストレージの簡素化された高度な管理を提供します。 
---
= Cloud Volumes ONTAPストレージ管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleは、 Cloud Volumes ONTAPストレージの簡素化された高度な管理を提供します。


CAUTION: すべてのディスクとアグリゲートはコンソールから直接作成および削除する必要があります。これらのアクションを別の管理ツールから実行しないでください。そうすると、システムの安定性に影響が及び、将来的にディスクを追加する能力が妨げられ、クラウド プロバイダーの料金が重複して発生する可能性があります。



[[storage-provisioning]]
== ストレージのプロビジョニング

コンソールを使用すると、ディスクを購入し、アグリゲートを管理することで、 Cloud Volumes ONTAPのストレージ プロビジョニングが簡単になります。ボリュームを作成するだけです。必要に応じて、高度な割り当てオプションを使用して、集約を自分でプロビジョニングすることもできます。



[[simplified-provisioning]]
=== 簡素化されたプロビジョニング

アグリゲートはボリュームにクラウド ストレージを提供します。インスタンスを起動するとき、および追加のボリュームをプロビジョニングするときに、コンソールによってアグリゲートが作成されます。

ボリュームを作成すると、コンソールは次の 3 つのうちのいずれかを実行します。

* 十分な空き領域がある既存のアグリゲートにボリュームを配置します。
* 既存のアグリゲート用にさらにディスクを購入して、そのアグリゲートにボリュームを配置します。
* 新しいアグリゲート用のディスクを購入し、そのアグリゲートにボリュームを配置します。


コンソールは、アグリゲートの最大サイズ、シン プロビジョニングが有効かどうか、アグリゲートの空き領域のしきい値など、いくつかの要素を確認して、新しいボリュームを配置する場所を決定します。



[[advanced-allocation]]
=== 高度な割り当て

集計を管理することもできます。link:task-create-aggregates.html["*高度な割り当て*ページから"] 、特定の数のディスクを含む新しいアグリゲートを作成したり、既存のアグリゲートにディスクを追加したり、特定のアグリゲートにボリュームを作成したりできます。



[[capacity-management]]
== 容量管理

組織またはアカウント管理者は、ストレージ容量の決定を通知したり、容量要件を自動的に管理するかどうかをコンソールで設定できます。

この動作は、コンソール エージェントの _容量管理モード_ によって決まります。容量管理モードは、そのコンソール エージェントによって管理されるすべてのCloud Volumes ONTAPシステムに影響します。別のコンソール エージェントがある場合は、別の方法で構成できます。



[[automatic-capacity-management]]
=== 自動容量管理

容量管理モードは、デフォルトで自動に設定されています。このモードでは、コンソールは 15 分ごとに空き領域比率をチェックし、空き領域比率が指定されたしきい値を下回っているかどうかを判断します。さらに容量が必要な場合は、新しいディスクの購入を開始し、使用されていないディスクのコレクション (アグリゲート) を削除し、必要に応じてアグリゲート間でボリュームを移動し、ディスク障害を防止します。

次の例は、このモードがどのように動作するかを示しています。

* アグリゲートが容量しきい値に達し、さらにディスクを追加する余裕がある場合、コンソールはボリュームが引き続き拡張できるように、そのアグリゲート用に新しいディスクを自動的に購入します。
* アグリゲートが容量のしきい値に達し、これ以上ディスクを追加できない場合、コンソールは自動的にそのアグリゲートから、空き容量のあるアグリゲート、または新しいアグリゲートにボリュームを移動します。
+
コンソールがボリューム用に新しいアグリゲートを作成する場合、そのボリュームのサイズに対応できるディスクサイズを選択します。

+
元のアグリゲートに空き容量が確保されたことを確認してください。既存のボリュームでも新規のボリュームでも、そのスペースを使用できます。このシナリオでは、スペースをクラウド プロバイダに返却することはできません。

* アグリゲートにボリュームが 12 時間以上含まれていない場合、コンソールはそれを削除します。




==== 自動容量管理によるLUNの管理

コンソールの自動容量管理は LUN には適用されません。  LUN を作成すると、自動拡張機能が無効になります。



[[manual-capacity-management]]
=== 手動容量管理

組織またはアカウント管理者が *容量管理モード* を手動に設定した場合、コンソールは容量の決定に対して適切なアクションを実行するように通知します。自動モードで説明したのと同じ例が手動モードにも当てはまりますが、アクションを受け入れるかどうかはユーザー次第です。

.関連リンク
* link:task-manage-capacity-settings.html["容量管理モードを変更する方法を学ぶ"] 。
* AWS の情報プロビジョニングについては、link:reference-configs-aws.html["AWSにおけるアグリゲートのディスクプロビジョニング"]を参照してください。

