---
sidebar: sidebar 
permalink: concept-flash-cache.html 
keywords: cloud volumes ontap, flash cache, read-intensive, read, random, databases, email, file services, compression, performance, nvme 
summary: 一部のCloud Volumes ONTAP構成にはローカル NVMe ストレージが含まれており、 Cloud Volumes ONTAP はこれをフラッシュ キャッシュとして使用してパフォーマンスを向上させます。 
---
= Flash Cache
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
一部のCloud Volumes ONTAP構成にはローカル NVMe ストレージが含まれており、 Cloud Volumes ONTAP はこれを _フラッシュ キャッシュ_ として使用してパフォーマンスを向上させます。



== フラッシュキャッシュとは何ですか?

Flash Cache は、最近読み取られたユーザー データとNetAppメタデータをリアルタイムでインテリジェントにキャッシュすることで、データへのアクセスを高速化します。これは、データベース、電子メール、ファイル サービスなどのランダム読み取り集中型のワークロードに効果的です。



== サポートされている構成

Flash Cache は、特定のCloud Volumes ONTAP構成でサポートされます。サポートされている構成については、 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Cloud Volumes ONTAPリリースノート"^]



== 制限事項

ifdef::aws[]

* AWS でCloud Volumes ONTAP 9.12.0 以前の Flash Cache を構成する場合、Flash Cache のパフォーマンス向上を活用するには、すべてのボリュームで圧縮を無効にする必要があります。  Cloud Volumes ONTAP 9.12.1 以降をデプロイまたはアップグレードする場合は、圧縮を無効にする必要はありません。
+
NetApp Consoleからボリュームを作成するときにストレージ効率設定の選択をスキップするか、ボリュームを作成してから http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["CLIを使用してデータ圧縮を無効にする"^]。



endif::aws[]

* 再起動後のキャッシュの再ウォームアップは、 Cloud Volumes ONTAPではサポートされていません。

