---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP には、信頼性の高い運用を実現するために、AWS でのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。 
---
= AWS のCloud Volumes ONTAPのストレージ制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAPには、信頼性の高い操作を実現するために、ストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。



[[maximum-system-capacity-by-license]]
== ライセンスによる最大システム容量

最大システム容量には、ディスクベースのストレージと、データ階層化に使用されるオブジェクト ストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量制限に達した場合、NetApp Console は対応が必要なメッセージを表示し、追加ディスクの追加ができなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に到達できなくなります。このような場合は、 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]容量制限に到達できます。詳細については、以下の容量とディスク制限を参照してください。

[[cap-license-aws]]
.容量ベースのライセンスの容量制限
容量ベースのライセンスでは、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された総容量は、クラウド プロバイダのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保するために https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]に従う必要があります。詳細については、 https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWSのドキュメント"^]を参照してください。

他のライセンス タイプの容量制限::


[cols="25,75"]
|===
| ライセンス | 最大システム容量（ディスク+オブジェクトストレージ） 


| フリーミアム | 500ギガバイト 


| PAYGO Explore | 2 TiB（Explore ではデータ階層化はサポートされていません） 


| PAYGO Standard | 10 TiB 


| PAYGO Premium | 368 TiB 


| ノードベースのライセンス | 2 PiB（複数のライセンスが必要） 
|===
.HAの場合、ライセンス容量の制限はノードごとですか、それともHAペア全体に対してですか？
容量制限は HA ペア全体に適用されます。ノードごとではありません。たとえば、Premiumライセンスでは、両方のノードで最大368 TiBが許可されます。

.AWS の HA システムの場合、ミラーリングされたデータは容量制限にカウントされますか？
いいえ、違います。AWS HAペアのデータはノード間で同期的にミラーリングされるため、障害発生時にもデータを利用できます。たとえば、ノードAで8 TiBのディスクを購入した場合、Consoleはミラーリングされたデータに使用されるノードBにも8 TiBのディスクを割り当てます。16 TiBの容量がプロビジョニングされましたが、ライセンス制限にカウントされるのは8 TiBのみです。



[[aggregate-limits]]
== アグリゲートの制限

Cloud Volumes ONTAPはEBSボリュームをディスクとして使用し、それらを_アグリゲート_にグループ化します。アグリゲートはボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限 


| アグリゲートの最大数 | 単一ノード：ディスク制限と同じ HAペア：ノードあたり18個 ^1^ 


| 最大アグリゲート サイズ^2^  a| 
* 96 TiBのRaw容量
* Elastic Volumes による 128 TiB の raw 容量 ^3^




| アグリゲートあたりのディスク数 ^4^  a| 
* 1-6
* Elastic Volumes 付き 4 または 8 ^3^




| アグリゲートあたりの RAID グループの最大数 | 2 
|===
注：

. データ ディスクの制限を超えてしまうため、HAペアの両方のノードに18個のアグリゲートを作成することはできません。
. 最大アグリゲート サイズはディスクに依存しており、データ階層化に使用するオブジェクト ストレージは含まれません。
. Amazon EBS Elastic Volumes 機能をサポートする設定がある場合、アグリゲートには最大 8 個のディスクを含めることができ、最大 128 TiB の容量が提供されます。デフォルトでは、Cloud Volumes ONTAP 9.11.0 以降のシステムでは、gp3 または io1 ディスクを使用する場合に Amazon EBS Elastic Volumes が有効になります。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["エラスティックボリュームのサポートについて詳しくはこちら"^]
. アグリゲート内のすべてのディスクは同じサイズである必要があります。




[[disk-and-tiering-limits-by-ec2-instance]]
== EC2 インスタンスごとのディスクと階層化の制限

容量制限は、使用する EC2 インスタンスタイプファミリーと、単一ノードシステムを使用しているか HA ペアを使用しているかによって異なります。

以下の注記には、下の表に表示される数値に関する詳細が記載されています。

* ディスク制限は、ユーザー データが含まれるディスクに固有です。
+
制限にはブート ディスクとルート ディスクは含まれません。

* ディスクのみを使用する場合と、ディスクとオブジェクト ストレージへのコールド データ階層化を使用する場合の最大システム容量がリストされます。
* Cloud Volumes ONTAPはEBSボリュームをディスクとして使用します。最大ディスク サイズは16 TiBです。




[[limits-for-different-deployment-modes-of-capacity-based-licensing]]
=== 容量ベースのライセンスのさまざまな導入モードの制限

以下のディスク制限は、容量ベースのライセンス パッケージを使用する Cloud Volumes ONTAP システムに適用されます。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP ライセンス オプションについて説明します"^]


NOTE: 単一ノードおよびHA構成の最大システム容量とデータ階層化容量の制限については、<<cap-license-aws>>を参照してください。



==== シングル ノード

[cols="18,18,32,width=100%,options="]
|===


| Instance | ノードあたりの最大ディスク数 | ディスクのみでの最大システム容量 


| c5、m5、r5 インスタンス | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== HAペア

[cols="18,18,32,width=100%,options="]
|===


| Instance | ノードあたりの最大ディスク数 | ディスクのみでの最大システム容量 


| c5、m5、r5 インスタンス | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256 TiB 
|===
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




[[limits-for-different-deployment-modes-of-node-based-licensing]]
=== ノードベース ライセンスのさまざまな導入モードの制限

以下のディスク制限は、ノードベースのライセンスを使用する Cloud Volumes ONTAP システムに適用されます。これは、ノードごとに Cloud Volumes ONTAP のライセンスを取得できるようにした前世代の ライセンス モデル です。ノードベースのライセンスは、既存のお客様も引き続き利用できます。

Cloud Volumes ONTAP BYOL シングルノードまたは HA ペア システムに複数のノードベースのライセンスを購入して、368 TiB を超える容量を割り当て、テスト済みおよびサポートされている最大システム容量制限の 2 PiB まで使用できます。ディスク制限により、ディスクのみを使用すると容量制限に到達できなくなる可能性があることに注意してください。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP に追加のシステム ライセンスを追加する方法を学ぶ"^]によって、ディスク制限を超えることができます。Cloud Volumes ONTAP はテスト済みおよびサポートされている最大システム容量である 2 PiB までサポートされますが、2 PiB の制限を超えると、サポートされていないシステム構成になります。

AWS Secret CloudとTop Secret Cloudのリージョンでは、Cloud Volumes ONTAP 9.12.1以降で複数のノードベースのライセンスの購入がサポートされています。



==== PAYGO Premiumを使用するシングルノード

[cols="18,18,32,32"]
|===
| Instance | ノードあたりの最大ディスク数 | ディスクのみでの最大システム容量 | ディスクとデータ階層化による最大システム容量 


| c5、m5、r5 インスタンス | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. 21個のデータディスクは、Cloud Volumes ONTAPの_新規_導入時の制限です。バージョン9.7以前で作成されたシステムをアップグレードする場合、システムは引き続き22個のディスクをサポートします。9.8リリース以降、コアディスクが追加されたため、これらのインスタンスタイプを使用する新しいシステムではサポートされるデータディスクが1つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== BYOL による単一ノード

[cols="18,18,16,16,16,16"]
|===
| Instance | ノードあたりの最大ディスク数 2+| 1つのライセンスによる最大システム容量 2+| 複数のライセンスによる最大システム容量 


2+|  | *ディスクのみ* | *ディスク+データ階層化* | *ディスクのみ* | *ディスク+データ階層化* 


| c5、m5、r5 インスタンス | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. 21個のデータディスクは、Cloud Volumes ONTAPの_新規_導入時の制限です。バージョン9.7以前で作成されたシステムをアップグレードする場合、システムは引き続き22個のディスクをサポートします。9.8リリース以降、コアディスクが追加されたため、これらのインスタンスタイプを使用する新しいシステムではサポートされるデータディスクが1つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== PAYGO PremiumのHAペア

[cols="18,18,32,32"]
|===
| Instance | ノードあたりの最大ディスク数 | ディスクのみでの最大システム容量 | ディスクとデータ階層化による最大システム容量 


| c5、m5、r5 インスタンス | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB 
|===
. 18個のデータディスクは、Cloud Volumes ONTAPの_新規_導入時の制限です。バージョン9.7以前で作成されたシステムをアップグレードする場合、システムは引き続き19個のディスクをサポートします。9.8リリース以降、コアディスクが追加されたため、これらのインスタンスタイプを使用する新しいシステムではサポートされるデータディスクが1つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== BYOLを使用したHAペア

[cols="18,18,16,16,16,16"]
|===
| Instance | ノードあたりの最大ディスク数 2+| 1つのライセンスによる最大システム容量 2+| 複数のライセンスによる最大システム容量 


2+|  | *ディスクのみ* | *ディスク+データ階層化* | *ディスクのみ* | *ディスク+データ階層化* 


| c5、m5、r5 インスタンス | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB | 256 TiB | 2 PiB 
|===
. 18個のデータディスクは、Cloud Volumes ONTAPの_新規_導入時の制限です。バージョン9.7以前で作成されたシステムをアップグレードする場合、システムは引き続き19個のディスクをサポートします。9.8リリース以降、コアディスクが追加されたため、これらのインスタンスタイプを使用する新しいシステムではサポートされるデータディスクが1つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




[[storage-vm-limits]]
== Storage VMの制限

一部の構成では、Cloud Volumes ONTAP 用に追加のストレージ VM （ SVM ）を作成できます。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["追加のストレージ VM を作成する方法を学ぶ"^]。

[cols="40,60"]
|===
| ライセンス タイプ | Storage VMの制限 


| *フリーミアム*  a| 
合計24台のストレージVM ^1,2^



| *容量ベースのPAYGOまたはBYOL* ^3^  a| 
合計24台のストレージVM ^1,2^



| *ノードベースのPAYGO*  a| 
* データを提供するための 1 つのストレージ VM
* ディザスタ リカバリ用のストレージ VM × 1




| *ノードベースのBYOL* ^4^  a| 
* 合計24台のストレージVM ^1,2^


|===
. 使用する EC2 インスタンス タイプによっては、制限が低くなる場合があります。インスタンスごとの制限については、以下のセクションに記載されています。
. これら 24 台のストレージ VM は、データを提供したり、ディザスタ リカバリ（DR）用に構成したりできます。
. 容量ベースのライセンスの場合、追加のストレージVMに対して追加のライセンス コストは発生しませんが、ストレージVMごとに4TiBの最小容量料金が発生します。たとえば、2つのストレージVMを作成し、それぞれに2TiBのプロビジョニングされた容量がある場合、合計8TiBが課金されます。
. ノードベースのBYOLの場合、Cloud Volumes ONTAPにデフォルトで付属する最初のストレージVM以外の追加の_データ提供_ストレージVMごとにアドオンライセンスが必要です。ストレージVMアドオンライセンスを取得するには、アカウントチームにお問い合わせください。
+
災害復旧（DR）用に構成するStorage VMにはアドオン ライセンスは必要ありません（無料）が、Storage VMの制限にカウントされます。たとえば、データ サービスStorage VMが12台、災害復旧用にStorage VMが12台構成されている場合、制限に達しているため、追加のStorage VMを作成することはできません。





[[storage-vm-limit-by-ec2-instance-type]]
=== EC2 インスタンス タイプ別のStorage VM制限

追加のストレージ VM を作成する場合は、ポート e0a にプライベート IP アドレスを割り当てる必要があります。以下の表は、インターフェースあたりのプライベート IP の最大数と、Cloud Volumes ONTAP の導入後にポート e0a で使用可能な IP アドレスの数を示しています。使用可能な IP アドレスの数は、その構成のストレージ VM の最大数に直接影響します。

以下にリストされているインスタンスは、c5、m5、および r5 インスタンス ファミリ用です。

[cols="6*"]
|===
| 構成 | インスタンスタイプ | インターフェースあたりの最大プライベート IP 数 | 展開後に残る IP 数 ^1^ | 管理 LIF なしの最大ストレージ VM 数^2,3^ | 管理 LIF を備えた最大ストレージ VM 数^2,3^ 


.9+| *単一ノード* | *.xlarge | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *単一 AZ の HA ペア* | *.xlarge | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *マルチAZのHAペア* | *.xlarge | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. この数字は、Cloud Volumes ONTAPの導入とセットアップ後にポートe0aで利用可能な_残りの_プライベートIPアドレスの数を示します。たとえば、*.2xlargeシステムは、ネットワーク インターフェイスごとに最大15個のIPアドレスをサポートします。単一のAZにHAペアを導入すると、ポートe0aに5つのプライベートIPアドレスが割り当てられます。その結果、*.2xlargeインスタンス タイプを使用するHAペアには、追加のストレージVM用に10個のプライベートIPアドレスが残ります。
. これらの列にリストされる数には、NetApp Consoleがデフォルトで作成する初期ストレージVMが含まれます。たとえば、この列に24と表示されている場合は、合計24個のストレージVMを追加で23個作成できることを意味します。
. ストレージ VM の管理 LIF はオプションです。管理 LIF は、SnapCenter などの管理ツールへの接続を提供します。
+
プライベート IP アドレスが必要であるため、作成できる追加のストレージ VM の数が制限されます。唯一の例外は、複数の AZ 内の HA ペアです。その場合、管理 LIF の IP アドレスは _フローティング_ IP アドレスなので、_プライベート_ IP 制限にはカウントされません。





[[file-and-volume-limits]]
== ファイルとボリュームの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限 


.2+| *ファイル* | 最大サイズ ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリューム サイズに依存、最大20億個 


| *FlexClone ボリューム* | 階層的クローンの深さ ^1^ | 499 


.3+| *FlexVol ボリューム* | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ ^3^ | 300 TiB 


| * Qtree * | FlexVolあたりの最大数 | 4,995 


| *Snapshot コピー* | FlexVolあたりの最大数 | 1,023 
|===
. 階層型クローンの深さは、1つのFlexVol volumeから作成できる入れ子階層のFlexClone volumesの最大深度です。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、上限は16TBです。
. FlexVol ボリュームの作成は、次のツールと最小バージョンを使用して、最大サイズ 300 TiB までサポートされます：
+
** System ManagerおよびONTAP CLI（Cloud Volumes ONTAP 9.12.1 P2および9.13.0 P2以降）
** Cloud Volumes ONTAP 9.13.1以降






[[iscsi-storage-limits]]
== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限 


.4+| *LUN* | ノードあたりの最大数 | 1,024 


| LUNマップの最大数 | 1,024 


| 最大サイズ | 16 TiB 


| ボリュームあたりの最大数 | 512 


| * igroup * | ノードあたりの最大数 | 256 


.2+| *イニシエーター* | ノードあたりの最大数 | 512 


| igroupあたりの最大数 | 128 


| *iSCSI セッション* | ノードあたりの最大数 | 1,024 


.2+| *LIF* | ポートあたりの最大数 | 32 


| ポートセットあたりの最大数 | 32 


| *portset* | ノードあたりの最大数 | 256 
|===