---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP には、信頼性の高い運用を実現するために、Google Cloud でのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。 
---
= Google CloudのCloud Volumes ONTAPのストレージ制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAPには、信頼性の高い操作を実現するために、ストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。



[[maximum-system-capacity-by-license]]
== ライセンスによる最大システム容量

Cloud Volumes ONTAPシステムの最大システム容量は、ライセンスによって決まります。最大システム容量には、ディスクベースのストレージと、データ階層化に使用されるオブジェクト ストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量制限に達した場合、NetApp Console は対応が必要なメッセージを表示し、追加ディスクの追加ができなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に到達できなくなります。容量制限に達するには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。詳細については、以下のディスク制限を参照してください。

[[cap-license-gcp]]
.容量ベースのライセンスの容量制限
容量ベースのライセンスでは、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された総容量は、クラウド プロバイダのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保するために https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]に従う必要があります。詳細については、 https://cloud.google.com/storage/docs/buckets["Google Cloud ドキュメント"^]を参照してください。

他のライセンス タイプの容量制限::


[cols="25,75"]
|===
| ライセンス | 最大システム容量（ディスク+オブジェクトストレージ） 


| フリーミアム | 500 GB 


| PAYGO Explore | 2 TB（Explore ではデータ階層化はサポートされていません） 


| PAYGO Standard | 10 TB 


| PAYGO Premium | 368 TB 


| ノードベースのライセンス | 2 PiB（複数のライセンスが必要） 
|===
.HA ペアの場合、ライセンス容量の制限はノードごとですか、それとも HA ペア全体に対してですか？
容量制限は HA ペア全体に適用されます。ノードごとではありません。たとえば、Premium ライセンスを使用する場合、両方のノード間で最大 368 TB の容量を持つことができます。

.HA ペアの場合、ミラーリングされたデータはライセンス容量制限にカウントされますか？
いいえ、違います。HAペアのデータはノード間で同期的にミラーリングされるため、Google Cloudで障害が発生した場合でもデータを利用できます。たとえば、ノードAで8 TBのディスクを購入した場合、NetApp Consoleはミラー化されたデータに使用されるノードBにも8 TBのディスクを割り当てます。16 TBの容量が設定されていますが、ライセンス制限にカウントされるのは8 TBのみです。



[[aggregate-limits]]
== アグリゲートの制限

Cloud Volumes ONTAP は Google Cloud Platform ディスクを _アグリゲート_ にグループ化します。アグリゲートはボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限 


| データアグリゲートの最大数 ^1^  a| 
* 単一ノードの場合は99
* HAペア全体で64




| 最大アグリゲート サイズ | 256 TB の raw 容量 ^2^ 


| アグリゲートあたりのディスク数 | 1-6 ^3^ 


| アグリゲートあたりの RAID グループの最大数 | 1 
|===
注：

. データ アグリゲートの最大数にはルート アグリゲートは含まれません。
. アグリゲートを構成するディスクによって、アグリゲートの容量制限が決まります。この制限には、データ階層化に使用されるオブジェクト ストレージは含まれません。
. アグリゲート内のすべてのディスクは同じサイズである必要があります。




[[disk-and-tiering-limits]]
== ディスクと階層化の制限

以下の表は、ディスクのみを使用した場合の最大システム容量、およびディスクとオブジェクト ストレージへのコールド データ階層化を使用した場合の最大システム容量を示しています。ディスク制限は、ユーザー データが含まれるディスクに固有です。制限にはブート ディスク、ルート ディスク、またはNVRAMは含まれません。

[cols="60,40"]
|===
| パラメータ | 制限 


| 最大データディスク数  a| 
* 単一ノードシステムの場合は124
* HAペアの場合、ノードあたり123




| 最大ディスク サイズ | 64 TB 


| ディスクのみの最大システム容量 | 256 TB ^1^ 


| ディスクと Google Cloud Storage バケットへのコールド データ階層化による最大システム容量 | ライセンスによって異なります。上記の最大システム容量制限を参照してください。 
|===
^1^ この制限は、Google Cloud Platform の仮想マシンの制限によって定義されます。



[[storage-vm-limits]]
== Storage VMの制限

一部の構成では、Cloud Volumes ONTAP 用に追加のストレージ VM （ SVM ）を作成できます。

これらはテストされた制限です。ストレージ VM をこれ以上設定することはサポートされていません。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["追加のストレージ VM を作成する方法を学ぶ"^]。

[cols="2*"]
|===
| ライセンス タイプ | Storage VMの制限 


| *フリーミアム*  a| 
ストレージ VM 合計 24 台 ^1^



| *容量ベースの PAYGO または BYOL* ^2^  a| 
ストレージ VM 合計 24 台 ^1^



| *ノードベースのBYOL* ^3^  a| 
ストレージ VM 合計 24 台 ^1^



| *ノードベースのPAYGO*  a| 
* データを提供するための 1 つのストレージ VM
* ディザスタ リカバリ用のストレージ VM × 1


|===
. これら 24 台のストレージ VM は、データを提供したり、ディザスタ リカバリ（DR）用に構成したりできます。
. 容量ベースのライセンスの場合、追加のストレージVMに対して追加のライセンス コストは発生しませんが、ストレージVMごとに4TiBの最小容量料金が発生します。たとえば、2つのストレージVMを作成し、それぞれに2TiBのプロビジョニングされた容量がある場合、合計8TiBが課金されます。
. ノードベースのBYOLの場合、Cloud Volumes ONTAPにデフォルトで付属する最初のストレージVM以外の追加の_データ提供_ストレージVMごとにアドオンライセンスが必要です。ストレージVMアドオンライセンスを取得するには、アカウントチームにお問い合わせください。
+
災害復旧（DR）用に構成するStorage VMにはアドオン ライセンスは必要ありません（無料）が、Storage VMの制限にカウントされます。たとえば、データ サービスStorage VMが12台、災害復旧用にStorage VMが12台構成されている場合、制限に達しているため、追加のStorage VMを作成することはできません。





[[logical-storage-limits]]
== 論理ストレージの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限 


.2+| *ファイル* | 最大サイズ ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリューム サイズに依存、最大20億個 


| *FlexClone ボリューム* | 階層的クローンの深さ ^12^ | 499 


.3+| *FlexVol ボリューム* | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ ^3^ | 300 TiB 


| * Qtree * | FlexVolあたりの最大数 | 4,995 


| *Snapshot コピー* | FlexVolあたりの最大数 | 1,023 
|===
. 階層型クローンの深さは、1つのFlexVol volumeから作成できる入れ子階層のFlexClone volumesの最大深度です。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、上限は16TBです。
. FlexVol ボリュームの作成は、次のツールと最小バージョンを使用して、最大サイズ 300 TiB までサポートされます：
+
** System Manager と ONTAP CLI （Cloud Volumes ONTAP 9.12.1 P2 および 9.13.0 P2 以降）
** Cloud Volumes ONTAP 9.13.1以降






[[iscsi-storage-limits]]
== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限 


.4+| *LUN* | ノードあたりの最大数 | 1,024 


| LUNマップの最大数 | 1,024 


| 最大サイズ | 16 TB 


| ボリュームあたりの最大数 | 512 


| * igroup * | ノードあたりの最大数 | 256 


.2+| *イニシエーター* | ノードあたりの最大数 | 512 


| igroupあたりの最大数 | 128 


| *iSCSI セッション* | ノードあたりの最大数 | 1,024 


.2+| *LIF* | ポートあたりの最大数 | 1 


| ポートセットあたりの最大数 | 32 


| *portset* | ノードあたりの最大数 | 256 
|===


[[cloud-volumes-ontap-ha-pairs-do-not-support-immediate-storage-giveback]]
== Cloud Volumes ONTAP HAペアは即時ストレージギブバックをサポートしていません

ノードが再起動した後、パートナーはストレージを返す前にデータを同期する必要があります。データの再同期にかかる時間は、ノードがダウンしている間にクライアントによって書き込まれたデータの量と、ギブバック時のデータ書き込み速度によって異なります。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Google Cloud で実行される Cloud Volumes ONTAP HA ペアでのストレージの仕組みを学ぶ"^]。
