---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Google Cloud Storage では、データがディスクに書き込まれる前に常に暗号化されますが、コンソール API を使用して、顧客管理の暗号化キーを使用するCloud Volumes ONTAPシステムを作成できます。これらは、Cloud Key Management Service を使用して GCP で生成および管理するキーです。 
---
= Cloud Volumes ONTAPで顧客管理の暗号化キーを使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud Storage では、データがディスクに書き込まれる前に常に暗号化されますが、API を使用して、_顧客管理の暗号化キー_ を使用するCloud Volumes ONTAPシステムを作成できます。これらは、Cloud Key Management Service を使用して GCP で生成および管理するキーです。

.手順
. キーが保存されているプロジェクトにおいて、コンソール エージェント サービス アカウントにプロジェクト レベルでの適切な権限があることを確認します。
+
権限は、 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["デフォルトのサービスアカウント権限"^]ただし、Cloud Key Management Service に代替プロジェクトを使用する場合は適用されない可能性があります。

+
権限は次のとおりです。

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. サービスアカウントが https://cloud.google.com/iam/docs/service-agents["Google Compute Engine サービス エージェント"^]キーに対する Cloud KMS 暗号化/復号化権限を持っています。
+
サービス アカウントの名前は、「service-[service_project_number]@compute-system.iam.gserviceaccount.com」という形式になります。

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Google Cloud ドキュメント: Cloud KMS での IAM の使用 - リソースに対するロールの付与"]

. getコマンドを呼び出してキーの「ID」を取得します。 `/gcp/vsa/metadata/gcp-encryption-keys` API 呼び出し、または GCP コンソールのキーで「リソース名のコピー」を選択します。
. 顧客管理の暗号化キーを使用し、データをオブジェクト ストレージに階層化する場合、 NetApp Consoleは永続ディスクの暗号化に使用されるのと同じキーを利用しようとします。ただし、まず Google Cloud Storage バケットがキーを使用できるようにする必要があります。
+
.. Google Cloud Storageサービスエージェントを見つけるには、 https://cloud.google.com/storage/docs/getting-service-agent["Google Cloud ドキュメント: Cloud Storage サービス エージェントの取得"^] 。
.. 暗号化キーに移動し、Google Cloud Storage サービス エージェントに Cloud KMS 暗号化/復号化権限を割り当てます。


+
詳細については、 https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Google Cloud ドキュメント: 顧客管理の暗号鍵の使用"^]

. システムを作成するときに、API リクエストに「gcpEncryption」パラメータを使用します。
+
*例*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


参照 https://docs.netapp.com/us-en/bluexp-automation/index.html["NetApp Console自動化ドキュメント"^]「GcpEncryption」パラメータの使用に関する詳細については、こちらをご覧ください。
