---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Cloud Volumes ONTAPを導入する場合、ワークロード要件に一致する事前構成済みのシステムを選択することも、独自の構成を作成することもできます。独自の構成を選択する場合は、利用可能なオプションを理解する必要があります。 
---
= Google Cloud でCloud Volumes ONTAP構成を計画する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud にCloud Volumes ONTAP をデプロイする場合、ワークロード要件に一致する事前構成済みのシステムを選択するか、独自の構成を作成することができます。独自の構成を選択する場合は、利用可能なオプションを理解する必要があります。



== Cloud Volumes ONTAPライセンスを選択する

Cloud Volumes ONTAPにはいくつかのライセンス オプションがあります。各オプションにより、ニーズに合った消費モデルを選択できます。

* link:concept-licensing.html["Cloud Volumes ONTAPのライセンスオプションについて学ぶ"]
* link:task-set-up-licensing-google.html["ライセンスの設定方法を学ぶ"]




== サポートされている地域を選択してください

Cloud Volumes ONTAP は、ほとんどの Google Cloud リージョンでサポートされています。 https://bluexp.netapp.com/cloud-volumes-global-regions["サポートされている地域の完全なリストを見る"^] 。



== サポートされているマシンタイプを選択してください

Cloud Volumes ONTAP は、選択したライセンス タイプに応じて、いくつかのマシン タイプをサポートします。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google CloudでサポートされているCloud Volumes ONTAPの構成"^]



== ストレージ制限を理解する

Cloud Volumes ONTAPシステムの生の容量制限はライセンスに関連付けられています。追加の制限は、アグリゲートとボリュームのサイズに影響します。構成を計画する際には、これらの制限に注意する必要があります。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["Google CloudのCloud Volumes ONTAPのストレージ制限"^]



== Google Cloud でシステムのサイズを決定する

Cloud Volumes ONTAPシステムのサイズを設定すると、パフォーマンスと容量の要件を満たすことができます。マシン タイプ、ディスク タイプ、ディスク サイズを選択するときは、いくつかの重要なポイントに注意する必要があります。

機械の種類:: サポートされているマシンタイプについては、 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Cloud Volumes ONTAPリリースノート"^]次に、サポートされている各マシンタイプに関する Google の詳細を確認します。ワークロード要件を、マシンタイプの vCPU とメモリの数に合わせてください。各 CPU コアによってネットワーク パフォーマンスが向上することに注意してください。
+
--
詳細については、以下を参照してください。

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud ドキュメント: N1 標準マシンタイプ"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud ドキュメント: パフォーマンス"^]


--
ディスク タイプ:: Cloud Volumes ONTAPのボリュームを作成するときは、 Cloud Volumes ONTAP がディスクに使用する基盤となるクラウド ストレージを選択する必要があります。ディスク タイプは次のいずれかになります。
+
--
* _ゾーン SSD 永続ディスク_: SSD 永続ディスクは、高レートのランダム IOPS を必要とするワークロードに最適です。
* _ゾーンバランス永続ディスク_: これらの SSD は、GB あたりの IOPS を低くすることで、パフォーマンスとコストのバランスをとります。
* _ゾーン標準永続ディスク_: 標準永続ディスクは経済的で、順次読み取り/書き込み操作を処理できます。
+
詳細については、 https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud ドキュメント: ゾーン永続ディスク（標準および SSD）"^] 。



--
ディスク サイズ:: Cloud Volumes ONTAPシステムをデプロイするときは、初期ディスク サイズを選択する必要があります。その後は、NetApp Consoleでシステムの容量を管理できるようになりますが、アグリゲートを自分で構築する場合は、次の点に注意してください。
+
--
* アグリゲート内のすべてのディスクは同じサイズである必要があります。
* パフォーマンスを考慮しながら、必要なスペースを決定します。
* 永続ディスクのパフォーマンスは、ディスク サイズとシステムで使用可能な vCPU の数に応じて自動的に調整されます。
+
詳細については、以下を参照してください。

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud ドキュメント: ゾーン永続ディスク（標準および SSD）"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud ドキュメント: 永続ディスクとローカル SSD のパフォーマンスの最適化"^]




--




== デフォルトのシステムディスクを表示する

コンソールは、ユーザー データ用のストレージに加えて、 Cloud Volumes ONTAPシステム データ (ブート データ、ルート データ、コア データ、 NVRAM) 用のクラウド ストレージも購入します。計画のために、 Cloud Volumes ONTAP を展開する前にこれらの詳細を確認すると役立つ場合があります。

* link:reference-default-configs.html#google-cloud-single-node["Google Cloud のCloud Volumes ONTAPシステムデータのデフォルト ディスクを表示する"] 。
* https://docs.cloud.google.com/docs/quotas/overview["Google Cloud ドキュメント: Cloud Quota の概要"^]
+
Google Cloud Compute Engine はリソース使用量に割り当て制限を適用するため、 Cloud Volumes ONTAP をデプロイする前に制限に達していないことを確認する必要があります。




TIP: コンソール エージェントにはシステム ディスクも必要です。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["コンソールエージェントのデフォルト構成の詳細を表示する"^] 。



== ネットワーク情報を収集する

Google CloudにCloud Volumes ONTAPを導入する場合は、仮想ネットワークに関する詳細を指定する必要があります。ワークシートを使用して、管理者から情報を収集できます。

*単一ノードシステムのネットワーク情報*

[cols="30,70"]
|===
| Google Cloud 情報 | あなたの価値 


| リージョン |  


| ゾーン |  


| VPCネットワーク |  


| サブネット |  


| ファイアウォール ポリシー（独自のものを使用している場合） |  
|===
*複数のゾーンにあるHAペアのネットワーク情報*

[cols="30,70"]
|===
| Google Cloud 情報 | あなたの価値 


| リージョン |  


| ノード1のゾーン |  


| ノード2のゾーン |  


| 調停者のためのゾーン |  


| VPC-0とサブネット |  


| VPC-1とサブネット |  


| VPC-2とサブネット |  


| VPC-3とサブネット |  


| ファイアウォール ポリシー（独自のものを使用している場合） |  
|===
*単一ゾーン内のHAペアのネットワーク情報*

[cols="30,70"]
|===
| Google Cloud 情報 | あなたの価値 


| リージョン |  


| ゾーン |  


| VPC-0とサブネット |  


| VPC-1とサブネット |  


| VPC-2とサブネット |  


| VPC-3とサブネット |  


| ファイアウォール ポリシー（独自のものを使用している場合） |  
|===


== 書き込み速度を選択する

コンソールを使用すると、Google Cloud の高可用性（HA）ペアを除き、 Cloud Volumes ONTAPの書き込み速度設定を選択できます。書き込み速度を選択する前に、標準設定と高速設定の違い、および高速書き込み速度を使用する場合のリスクと推奨事項を理解しておく必要があります。link:concept-write-speed.html["書き込み速度について詳しくはこちら"] 。



== ボリューム使用プロファイルを選択する

ONTAPには、必要なストレージの総量を削減できるいくつかのストレージ効率機能が含まれています。コンソールでボリュームを作成するときに、これらの機能を有効にするプロファイルまたは無効にするプロファイルを選択できます。どのプロファイルを使用するかを決めるには、これらの機能について詳しく理解する必要があります。

NetAppストレージ効率機能には、次のような利点があります。

シンプロビジョニング:: 物理ストレージ プールに実際に存在するよりも多くの論理ストレージをホストまたはユーザーに提供します。ストレージ スペースを事前に割り当てるのではなく、データが書き込まれるときに各ボリュームにストレージ スペースが動的に割り当てられます。
重複排除:: 同一のデータ ブロックを見つけて、単一の共有ブロックへの参照に置き換えることで効率を向上します。この手法は、同じボリューム内に存在する冗長なデータ ブロックを排除することで、ストレージ容量の要件を削減します。
圧縮:: プライマリ、セカンダリ、アーカイブ ストレージのボリューム内のデータを圧縮することで、データの保存に必要な物理容量を削減します。

