---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP は、外部キー マネージャーを使用したNetApp Volume Encryption (NVE) とNetApp Aggregate Encryption (NAE) の両方をサポートします。外部キー マネージャーを設定すると、NVE と NAE はデフォルトで有効になります。' 
---
= NetApp暗号化ソリューションを使用してCloud Volumes ONTAP上のボリュームを暗号化する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP は、 NetApp Volume Encryption (NVE) とNetApp Aggregate Encryption (NAE) をサポートしています。 NVE と NAE は、ボリュームの FIPS 140-2 準拠の保存データ暗号化を可能にするソフトウェア ベースのソリューションです。link:concept-security.html["これらの暗号化ソリューションについて詳しく見る"] 。

NVE と NAE はどちらも外部キー マネージャーでサポートされます。

NVE を使用する場合は、クラウド プロバイダーのキー ボールトを使用してONTAP暗号化キーを保護するオプションがあります。

* AWS Key Management Service（9.12.0以降）
* Azure キー コンテナー (AKV)
* Google Cloud Key Management Service


外部キーマネージャを設定すると、新しいアグリゲートではデフォルトでNAEが有効になります。NAEアグリゲートの一部ではない新しいボリュームでは、デフォルトでNVEが有効になります（たとえば、外部キーマネージャを設定する前に作成された既存のアグリゲートがある場合など）。

Cloud Volumes ONTAPはオンボードキー管理をサポートしていません。

.開始する前に
お客様のCloud Volumes ONTAPシステムは、NetAppサポートに登録する必要があります。NetApp Volume Encryptionライセンスは、NetAppサポートに登録されている各Cloud Volumes ONTAPシステムに自動的にインストールされます。

* https://docs.netapp.com/us-en/console-setup-admin/task-adding-nss-accounts.html["NetApp サポートサイトアカウントをコンソールに追加する"^]
* link:task-registering.html["従量課金制システムを登録する"]



NOTE: NetApp Consoleは、中国リージョンに存在するシステムにはNVEライセンスをインストールしません。

.手順
. サポートされているキーマネージャーのリストを http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool"^]で確認してください。
+

TIP: 「Key Managers」ソリューションを検索してください。

. link:task-connecting-to-otc.html["Cloud Volumes ONTAP CLIへの接続"^]。
. 外部キー管理を設定します。
+
** AWS：link:task-aws-key-management.html["AWS Key Management Service"]
** Azure：link:task-azure-key-vault.html["Azure キー コンテナー (AKV)"]
** Google Cloud：link:task-google-key-manager.html["Google Cloud Key Management Service"]



