---
sidebar: sidebar 
permalink: task-getting-started-gcp.html 
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console 
summary: 数ステップでCloud Volumes ONTAP for Google Cloud を使い始めましょう。 
---
= Google Cloud における Cloud Volumes ONTAP の導入概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP をデプロイするには、まず Google Cloud サブスクリプションと Cloud Volumes ONTAP ライセンスについて理解しておく必要があります。また、Google Cloud プロジェクトおよび組織向けに NetApp Console エージェントが作成されていることを確認する必要があります。このトピックの情報の多くは、Cloud Volumes ONTAP のデプロイを開始する前に、Console のセットアップの一部として実行する必要があります。

[cols="20,35,25,25"]
|===
| Task | 説明 | 参照 | プライベートモード展開に関する注意事項 


 a| 
コンソールエージェントを作成する
 a| 
コンソールエージェントがまだない場合は、Cloud Volumes ONTAP をデプロイする前に作成してください。インターネットアクセスのないサブネットにデプロイする場合は、コンソールエージェントを手動でインストールし、そのエージェント上で実行されている NetApp Console にアクセスしてください。
 a| 
コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Google Cloud でコンソールエージェントを作成する"^]
 a| 
インターネットアクセスのないサブネットにデプロイする場合は、コンソールエージェントを手動でインストールし、そのコンソールエージェント上で動作している NetApp Console ユーザーインターフェースにアクセスしてください。コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["インターネット接続なしでコンソールエージェントを手動でインストールする"^]



 a| 
構成を計画する
 a| 
コンソールでは、ワークロード要件に一致する事前構成済みのパッケージが提供されており、独自の構成を作成することもできます。独自の構成を選択する場合は、利用可能なオプションを理解する必要があります。
 a| 
link:task-planning-your-config-gcp.html["構成を計画する"]
 a| 
プライベート環境での展開についても、同様の計画上の考慮事項が必要です。



 a| 
ネットワークを設定する
 a| 
. VPC とサブネットがコンソール エージェントとCloud Volumes ONTAP間の接続をサポートしていることを確認します。
. データ階層化を有効にする場合は、Cloud Volumes ONTAP のサブネットを Private Google Access 用に設定してください。
. HA ペアをデプロイする場合は、それぞれ独自のサブネットを持つ 4 つの VPC があることを確認してください。
. 共有 VPC を使用している場合は、コンソール エージェント サービス アカウントに _Compute Network User_ ロールを付与します。
. NetApp AutoSupportのターゲット VPC からのアウトバウンド インターネット アクセスを有効にします。

 a| 
参照：

* link:reference-networking-gcp.html["Google Cloudのネットワーク要件"]
* Google Cloud のドキュメントを参照してください： https://cloud.google.com/vpc/docs/configure-private-google-access["Private Google Accessの構成"^]

 a| 
AutoSupport のアウトバウンドインターネットアクセスは必須ではありません。その他のネットワーク要件はすべて変更ありません。



 a| 
サービスアカウントを設定する
 a| 
Cloud Volumes ONTAPでは、コールドデータをGoogle Cloudの低コストオブジェクトストレージに階層化するデータ階層化を有効にするため、およびボリュームを低コストオブジェクトストレージにバックアップするNetApp Backup and recoveryを有効にするために、Google Cloudサービスアカウントが必要です。
 a| 
* link:task-creating-gcp-service-account.html["サービスアカウントを設定する"]
* link:concept-data-tiering.html["データ階層化について"]
* を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recoveryに関するドキュメント"^]

 a| 
プライベートモードでの展開に関して、追加の考慮事項はありません。



 a| 
Google Cloud API を有効にする
 a| 
プロジェクトで必要な Google Cloud API を有効にしてください。Console エージェントを作成する際に、既にこれらの設定を有効にしている可能性があります。
 a| 
Google Cloud のドキュメントを参照してください：https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud API を有効にする"^]
 a| 
APIを有効にする必要があります。クラウド管理者と協力して、プライベート環境で必要なAPIを有効にしてください。



 a| 
コンソールから Cloud Volumes ONTAP を導入する
 a| 
前提条件をすべて満たしたら、ウィザードの手順に従って Google Cloud に Cloud Volumes ONTAP をデプロイする手順を完了できます。
 a| 
参照：

* link:task-quick-deploy-gcp.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-gcp.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]

 a| 
デプロイを開始する前に、NetApp から Cloud Volumes ONTAP ライセンスを購入済みであることを確認してください。プライベート環境のデプロイには、ノードベースの BYOL ライセンスが必要です。Marketplace サブスクリプションは、Cloud Volumes ONTAP の使用料金の請求には対応していません。ライセンスファイルを NetApp から入手し、デプロイ時にアップロードしてください。参照：

* link:concept-license-management.html["ノードベースBYOLのライセンス管理"]
* link:task-manage-node-licenses.html["ノードベースのBYOLライセンスを管理する"]
* link:task-quick-deploy-gcp.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-gcp.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]


|===
.関連リンク
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["コンソールエージェントの作成"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Linuxホストにコンソールエージェントソフトウェアをインストールする"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["コンソール エージェントの Google Cloud 権限"^]

