---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport は、システムの健全性をプロアクティブに監視し、 NetAppテクニカル サポートにメッセージを送信します。デフォルトでは、各ノードでAutoSupportが有効になっており、HTTPS トランスポート プロトコルを使用してテクニカル サポートにメッセージを送信します。  AutoSupport がこれらのメッセージを送信できることを確認することをお勧めします。 
---
= Cloud Volumes ONTAPのAutoSupport設定を確認する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport は、システムの健全性をプロアクティブに監視し、 NetAppテクニカル サポートにメッセージを送信します。デフォルトでは、各ノードでAutoSupportが有効になっており、HTTPS トランスポート プロトコルを使用してテクニカル サポートにメッセージを送信します。  AutoSupport がこれらのメッセージを送信できることを確認することをお勧めします。

必要な構成手順は、 Cloud Volumes ONTAP にアウトバウンドのインターネット接続があることを確認することだけです。詳細については、クラウド プロバイダーのネットワーク要件を参照してください。



== AutoSupportの要件

Cloud Volumes ONTAPノードには、システムの健全性をプロアクティブに監視し、 NetAppテクニカル サポートにメッセージを送信するNetApp AutoSupport用のアウトバウンド インターネット アクセスが必要です。

Cloud Volumes ONTAP がAutoSupportメッセージを送信できるように、ルーティングおよびファイアウォール ポリシーで次のエンドポイントへの HTTPS トラフィックを許可する必要があります。

* \https://mysupport.netapp.com/aods/asupmessage
* \https://mysupport.netapp.com/asupprod/post/1.0/postAsup


AutoSupportメッセージを送信するためのアウトバウンド インターネット接続が利用できない場合、 NetApp Consoleは、コンソール エージェントをプロキシ サーバーとして使用するようにCloud Volumes ONTAPシステムを自動的に構成します。唯一の要件は、コンソール エージェントのセキュリティ グループがポート 3128 経由の受信接続を許可していることを確認することです。コンソール エージェントを展開した後、このポートを開く必要があります。

Cloud Volumes ONTAPに厳密なアウトバウンド ルールを定義した場合は、 Cloud Volumes ONTAPセキュリティ グループがポート 3128 経由のアウトバウンド接続を許可していることも確認する必要があります。


TIP: HA ペアを使用している場合、HA メディエーターは発信インターネット アクセスを必要としません。

送信インターネット アクセスが利用可能であることを確認したら、 AutoSupportをテストして、メッセージを送信できることを確認できます。手順については、 https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAPドキュメント: AutoSupportのセットアップ"^] 。



== AutoSupport構成のトラブルシューティング

アウトバウンド接続が利用できず、コンソールがCloud Volumes ONTAPシステムをコンソール エージェントをプロキシ サーバーとして使用するように構成できない場合は、システムがAutoSupportメッセージを送信できないという通知がコンソールから表示されます。この問題に対処するには、次の手順に従ってください。

.手順
. ONTAP CLI を使用するには、 Cloud Volumes ONTAPシステムに安全に接続します (SSH を使用)。
+
link:task-connecting-to-otc.html["Cloud Volumes ONTAPへのSSH接続方法を学ぶ"] 。

. AutoSupportサブシステムの詳細なステータスを確認します。
+
`autosupport check show-details`

+
応答は次のようになります。

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
http-httpsカテゴリのステータスが `OK` これは、 AutoSupportが適切に構成されており、メッセージを送信できることを意味します。

. そうでない場合は、各Cloud Volumes ONTAPノードのプロキシ URL を確認します。
+
`autosupport show -fields proxy-url`

. プロキシ URL パラメータが空の場合は、コンソール エージェントをプロキシとして使用するようにCloud Volumes ONTAPを構成します。
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. AutoSupport のステータスを再度確認します。
+
`autosupport check show-details`

. ステータスがまだ失敗の場合、ポート経由でCloud Volumes ONTAPとコンソールエージェント間の接続があることを確認してください。 `3128`。
. 検証後もステータスが失敗の場合は、コンソール エージェントに SSH で接続します。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["コンソールエージェントの Linux VM への接続の詳細"^]

. へ移動 `/opt/application/netapp/cloudmanager/docker_occm/data/`。
. プロキシ設定ファイルを開く `squid.conf`。ファイルの構造は次のとおりです。
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. ファイルにCloud Volumes ONTAPシステムの CIDR ブロックのエントリがない場合は、新しいエントリを追加してアクセスを許可します。
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
次に例を示します。

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. 設定ファイルを編集した後、プロキシコンテナを再起動します。 `sudo`。次に、Docker または Podman のどちらを使用しているかに応じて、次のコマンドを実行します。
+
Dockerの場合は、 `docker restart squid`。

+
Podmanを使用している場合は、 `podman restart squid`。

. ONTAP CLI に戻り、 Cloud Volumes ONTAP がAutoSupportメッセージを送信できることを確認します。
+
`autosupport check show-details`



.関連リンク
* link:reference-networking-aws.html["AWS におけるCloud Volumes ONTAPのネットワーク要件"^]
* link:reference-networking-azure.html["Azure のCloud Volumes ONTAPのネットワーク要件"^]
* link:reference-networking-gcp.html["Google Cloud のCloud Volumes ONTAPのネットワーク要件"^]

