---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Azure Marketplace から Cloud Volumes ONTAP をデプロイする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure Marketplace の直接デプロイを使用すると、Cloud Volumes ONTAP を迅速かつ簡単にデプロイできます。Azure Marketplace から、数回クリックするだけで Cloud Volumes ONTAP をすばやくデプロイし、お客様の環境でその主要な機能と性能を検証できます。

このオファーの詳細については、以下を参照してください。link:concept-azure-mktplace-direct.html["NetApp ConsoleとマーケットプレイスでCloud Volumes ONTAP のサービスについて学ぶ"] 。

.タスク概要
Azure Marketplace の直接デプロイを使用してデプロイされた Cloud Volumes ONTAP システムには、以下の特性があります。Azure Marketplace を通じてデプロイされたスタンドアロン インスタンスの機能は、NetApp Console で検出されると変更されることに注意してください。

* 最新のCloud Volumes ONTAPバージョン (9.16.1 以降)。
* Cloud Volumes ONTAP の無料ライセンスは、最大500 GiBのプロビジョニング容量に対して提供されており、NetAppサポートはなく、有効期限もありません。500 GiBを超える容量を使用するには、有効なライセンス権限が必要となり、料金が発生する場合があります。Cloud Volumes ONTAP のすべての機能と高度な管理機能をご利用いただくには、Cloud Volumes ONTAP システムをコンソールに接続してください。コンソールを介した検出と管理には、コンソールアカウントに関連付けられた有効な Azure Marketplace サブスクリプションが必要です。
* 単一の可用性ゾーン (AZ) に高可用性 (HA) モードで構成され、デフォルトのシリアル番号でプロビジョニングされた 2 つのノード。ストレージ仮想マシン（ストレージVM）は、link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["柔軟なオーケストレーションモード"] 。
* デフォルトで作成されるインスタンスの集約。
* 500 GiB のプロビジョニング容量を持つ Premium SSD v2 マネージド ディスク、ルート ディスク、およびデータ ディスク。
* NFS、CIFS、iSCSI、NVMe/TCP データ サービスが備わった 1 つのデータ ストレージ VM がデプロイされています。追加のデータ ストレージ VM を追加することはできません。
* NFS、CIFS (SMB)、iSCSI、Autonomous Ransomware Protection (ARP)、 SnapLock、およびSnapMirrorのライセンスがインストールされています。
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAP温度に敏感なストレージ効率 (TSSE)"^]、ボリューム暗号化、および外部キー管理がデフォルトで有効になっています。
* 以下の機能はサポートされていません:
+
** FabricPool の階層化
** ストレージVMタイプの変更
** 高速書き込みモード




.開始する前に
* コンソールでデプロイされたシステムを検出および管理する場合は、コンソールアカウントが有効な Azure Marketplace サブスクリプションに関連付けられていることを確認してください。コンソールにシステムを検出するには、有効なサブスクリプションが必要です。
* ネットワーク要件を満たしていることを確認してくださいlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["単一 AZ での HA 展開"]Azure で。。 link:reference-networking-azure.html["Cloud Volumes ONTAP用の Azure ネットワークを設定する"] 。
* Cloud Volumes ONTAPをデプロイするには、次のいずれかの Azure ロールが割り当てられている必要があります。
+
** その `contributor`デフォルトの権限を持つロール。詳細については、 https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Microsoft Azure ドキュメント: Azure 組み込みロール"^] 。
** 次の権限を持つカスタム RBAC ロール。詳細については、 https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azure ドキュメント: Azure カスタム ロール"^] 。
+
[]
====
"permissions": [ { "actions": [ "Microsoft.AAD/register/action", "Microsoft.Resources/subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action", "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkSecurityGroups/write", "Microsoft.Network/networkInterfaces/write", "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/extensions/write", "Microsoft.Resources/deployments/validate/action", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Network/virtualNetworks/write", "Microsoft.Network/virtualNetworks/read", "Microsoft.Network/networkSecurityGroups/write", "Microsoft.Network/networkSecurityGroups/read", "Microsoft.Compute/disks/write", "Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.Resources/deployments/write", "Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Network/virtualNetworks/subnets/write" ], "notActions": [], "dataActions": [], "notDataActions": [] } ]

====
+

NOTE: リソースプロバイダー「Microsoft.storage」をサブスクリプションに登録している場合は、 `Microsoft.AAD/register/action`許可。詳細については、 https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azure ドキュメント: ストレージの Azure アクセス許可"^] 。





.手順
. Azure Marketplace サイトから NetApp 製品を検索します。
. * NetApp Cloud Volumes ONTAP direct*を選択します。
. *作成* をクリックして、デプロイメント ウィザードを起動します。
. プランを選択してください。  *プラン* リストには通常、 Cloud Volumes ONTAPの最新リリースが表示されます。
. *基本*タブで、次の詳細を入力します。
+
** *サブスクリプション*: サブスクリプションを選択します。デプロイメントはサブスクリプション番号にリンクされます。
** *リソース グループ*: 既存のリソース グループを使用するか、新しいリソース グループを作成します。リソース グループは、ディスクやストレージ VM などのすべてのリソースをCloud Volumes ONTAPシステムの単一のグループ内に割り当てるのに役立ちます。
** *リージョン*: 単一の AZ での Azure HA デプロイメントをサポートするリージョンを選択します。リストには利用可能なリージョンのみが表示されます。
** *サイズ*: サポートされている Premium SSD v2 マネージド ディスクのストレージ VM サイズを選択します。
** *ゾーン*: 選択した地域のゾーンを選択します。
** *管理者パスワード*: パスワードを設定します。デプロイメント後にシステムにログインするには、この管理者パスワードを使用します。
** *パスワードの確認*: 確認のために同じパスワードをもう一度入力します。
+
*** *ネットワーク* タブで、仮想ネットワークとサブネットを追加するか、リストから選択します。
+

NOTE: Microsoft Azure の制限に準拠するには、新しい仮想ネットワークを設定するときに新しいサブネットを作成する必要があります。同様に、既存のネットワークを選択する場合は、既存のサブネットを選択する必要があります。

*** 定義済みのネットワーク セキュリティ グループを選択するには、[*はい*] を選択します。必要なトラフィック ルールが定義された Azure ネットワーク セキュリティ グループを割り当てるには、[*いいえ*] を選択します。詳細については、 link:reference-networking-azure.html#security-group-rules["Azure のセキュリティ グループ ルール"] 。
*** *詳細*タブで、このデプロイメントに必要な 2 つの Azure 機能が設定されているかどうかを確認します。参照link:task-saz-feature.html["Cloud Volumes ONTAP の単一 AZ デプロイメントで Azure 機能を有効にする"]そしてlink:task-azure-high-availability-mode.html["AzureでCloud Volumes ONTAPの高可用性モードを有効にする"]。
*** *タグ* タブで、リソースまたはリソース グループの名前と値のペアを定義できます。
*** *確認 + 作成* タブで詳細を確認し、デプロイを開始します。






.終了後の操作
通知アイコンを選択して、デプロイメントの進行状況を表示します。  Cloud Volumes ONTAPがデプロイされた後、操作用にリストされたストレージ VM を表示できます。

アクセスできるようになったら、 ONTAP System Manager またはONTAP CLI を使用して、設定した管理者認証情報でストレージ VM にログインします。その後、ボリューム、LUN、または共有を作成し、 Cloud Volumes ONTAPのストレージ機能を使い始めることができます。



[[troubleshoot-deployment-issues]]
== デプロイメントの問題のトラブルシューティング

Azure Marketplace を通じて直接デプロイされた Cloud Volumes ONTAP システムには、NetApp のサポートは含まれません。導入中に何らかの問題が発生した場合は、お客様ご自身でトラブルシューティングを行い、解決することができます。

.手順
. Azure Marketplace サイトで、「ブート診断」>「シリアルログ」に移動します。
. シリアルログをダウンロードして調査します。
. トラブルシューティングについては、製品ドキュメントとナレッジベース (KB) の記事を参照してください。
+
** https://learn.microsoft.com/en-us/partner-center/["Azure Marketplace のドキュメント"]
** https://www.netapp.com/support-and-training/documentation/["NetAppのドキュメント"]
** https://kb.netapp.com/["NetApp KB記事"]






[[discover-the-deployed-systems-in-console]]
== コンソールで展開されたシステムを検出する

Azure Marketplace の直接デプロイを使用してデプロイした Cloud Volumes ONTAP システムを検出し、NetApp Console の「*システム*」ページで管理できます。NetApp Console エージェントはシステムを検出し、システムを追加して必要なライセンスを適用し、これらのシステムに対して NetApp Console のすべての機能を有効化します。PSSD v2 マネージドディスクを使用した単一の AZ における元の HA 構成は保持され、システムは元のデプロイメントと同じ Azure サブスクリプションおよびリソースグループに登録されます。

.タスク概要
Azure Marketplace の直接デプロイを使用してデプロイされた Cloud Volumes ONTAP システムを検出すると、コンソール エージェントは次のタスクを実行します：

* 検出されたシステムの無料ライセンスを通常の容量ベースのライセンスに置き換えますlink:concept-licensing.html#packages["フリーミアムライセンス"]。
* 展開されたシステムの既存の機能を保持し、データ保護、データ管理、セキュリティ機能などのコンソールの追加機能を追加します。
* ノードにインストールされているライセンスを、NFS、CIFS (SMB)、iSCSI、ARP、 SnapLock、およびSnapMirrorの新しいONTAPライセンスに置き換えます。
* 汎用ノードのシリアル番号を一意のシリアル番号に変換します。
* 必要に応じてリソースに新しいシステム タグを割り当てます。
* インスタンスの動的 IP アドレスを静的 IP アドレスに変換します。
* 以下の機能を有効にしますlink:task-tiering.html["FabricPool の階層化"]、link:task-verify-autosupport.html["AutoSupport"] 、 そしてlink:concept-worm.html["一度書き込み、何度も読み取り"]展開されたシステム上の (WORM) ストレージ。必要なときにコンソールからこれらの機能を有効にすることができます。
* インスタンスを検出するために使用される NSS アカウントにインスタンスを登録します。
* 容量管理機能を有効にするlink:concept-storage-management.html#capacity-management["自動モードと手動モード"]発見されたシステムについて。


.開始する前に
Azure Marketplace 上でデプロイが完了していることを確認してください。コンソール エージェントは、デプロイが完了し、システムが検出可能になった場合にのみ、システムを検出できます。

.手順
コンソールでは、既存のシステムを検出するための標準の手順に従います。。 link:task-adding-systems.html["既存のCloud Volumes ONTAPシステムをコンソールに追加する"] 。


CAUTION: 検出処理中にエラーメッセージが表示される場合がありますが、検出プロセスが完了するまでは無視して構いません。検出中は、Azure Marketplace ポータルでシステムが生成した Cloud Volumes ONTAP の構成（特にシステム タグ）を変更しないでください。これらの設定に変更を加えると、予期しないシステム動作が発生する可能性があります。

.終了後の操作
検出が完了すると、コンソールの *システム* ページにリストされているシステムを表示できます。次のようなさまざまな管理タスクを実行できます。link:task-manage-aggregates.html["総計を拡大する"] 、link:task-create-volumes.html["ボリュームの追加"] 、link:task-managing-svms-azure.html["追加のストレージVMのプロビジョニング"] 、 そしてlink:task-change-azure-vm.html["インスタンスタイプの変更"]。

.関連リンク
ストレージの作成の詳細については、 ONTAP のドキュメントを参照してください。

* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-subscriptions.html["新しいマーケットプレイスのサブスクリプションを追加する"^]
* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["NFS用のボリュームを作成する"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["iSCSI用のLUNを作成する"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["CIFSの共有を作成する"^]

