---
sidebar: sidebar 
permalink: task-getting-started-azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, BlueXP, cloud volumes ontap, cloud ontap, subscription, create 
summary: 数ステップでCloud Volumes ONTAP for Azure を使い始めましょう。 
---
= Azure における Cloud Volumes ONTAP の導入概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP をデプロイするには、まず Azure サブスクリプションと Cloud Volumes ONTAP ライセンスについて理解しておく必要があります。また、Azure サブスクリプションおよび組織向けに NetApp Console エージェントが作成されていることを確認する必要があります。このトピックの情報の多くは、Cloud Volumes ONTAP のデプロイを開始する前に、Console のセットアップの一部として実行する必要があります。

[cols="20,35,25,25"]
|===
| Task | 説明 | 参照 | プライベートモード展開に関する注意事項 


 a| 
コンソールエージェントを作成する
 a| 
コンソールエージェントがまだない場合は、Cloud Volumes ONTAP をデプロイする前に作成してください。
 a| 
コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Azureでコンソールエージェントを作成する"^]
 a| 
インターネットアクセスのないサブネットにデプロイする場合は、コンソールエージェントを手動でインストールし、そのコンソールエージェント上で動作している NetApp Console ユーザーインターフェースにアクセスしてください。コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["インターネット接続なしでコンソールエージェントを手動でインストールする"^]



 a| 
構成を計画する
 a| 
コンソールでは、ワークロード要件に一致する事前構成済みのパッケージが提供されており、独自の構成を作成することもできます。独自の構成を選択する場合は、利用可能なオプションを理解する必要があります。
 a| 
link:task-planning-your-config-azure.html["AzureでCloud Volumes ONTAPの構成を計画する"]
 a| 
プライベート環境での展開についても、同様の計画上の考慮事項が必要です。



 a| 
ネットワークを設定する
 a| 
. VNet とサブネットが Console エージェントと Cloud Volumes ONTAP 間の接続をサポートしていることを確認してください。
. ターゲット VNet から NetApp AutoSupport へのアウトバウンドインターネットアクセスを有効にします。

 a| 
link:reference-networking-azure.html["Azureのネットワーク要件"]
 a| 
AutoSupport のアウトバウンドインターネットアクセスは必須ではありません。その他のネットワーク要件はすべて変更ありません。



 a| 
コンソールから Cloud Volumes ONTAP を導入する
 a| 
前提条件をすべて満たしたら、ウィザードの手順に従って Azure に Cloud Volumes ONTAP をデプロイする手順を完了できます。
 a| 
参照：

* link:task-quick-deploy-azure.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-otc-azure.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]

 a| 
デプロイを開始する前に、NetApp から Cloud Volumes ONTAP ライセンスを購入済みであることを確認してください。プライベート環境のデプロイには、ノードベースの BYOL ライセンスが必要です。Marketplace サブスクリプションは、Cloud Volumes ONTAP の使用料金の請求には対応していません。ライセンスファイルを NetApp から入手し、デプロイ時にアップロードしてください。参照：

* link:concept-license-management.html["ノードベースBYOLのライセンス管理"]
* link:task-manage-node-licenses.html["ノードベースのBYOLライセンスを管理する"]
* link:task-quick-deploy-azure.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-otc-azure.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]


|===
.関連リンク
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["コンソールからコンソールエージェントを作成する"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-marketplace.html["Azure Marketplace からコンソール エージェントを作成する"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Linuxホストにコンソールエージェントソフトウェアをインストールする"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["コンソールが権限を使って行うこと"^]

