---
sidebar: sidebar 
permalink: task-saz-feature.html 
keywords: Microsoft Azure feature, HA in SAZ, single availability zone, Azure feature, Virtual Machine Scale Sets in Flexible mode, VMOrchestratorZonalMultiFD, VM Orchestrator, Zonal, MultiFD, Microsoft.Compute/VMOrchestratorZonalMultiFD feature 
summary: この Microsoft Azure 機能を有効にして、SAZ に HA を展開します。 
---
= Azure でCloud Volumes ONTAPの VMOrchestratorZonalMultiFD を有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ローカル冗長ストレージ（LRS）の単一アベイラビリティゾーン（AZ）にVMインスタンスを展開するには、Microsoft `Microsoft.Compute/VMOrchestratorZonalMultiFD`サブスクリプションの機能。高可用性 (HA) モードでは、この機能により、同じ可用性ゾーン内の別々の障害ドメインにノードを展開することが容易になります。

この機能を有効にしないと、ゾーン展開は行われず、以前の LRS 非ゾーン展開が有効になります。

単一のアベイラビリティゾーンでのVMの展開については、以下を参照してください。link:concept-ha-azure.html["Azureのハイアベイラビリティ ペア"] 。

「所有者」権限を持つユーザーとして次の手順を実行します。

.手順
. Azure ポータルから Azure Cloud Shell にアクセスします。詳細については、 https://learn.microsoft.com/en-us/azure/cloud-shell/get-started/["Microsoft Azure ドキュメント: Azure Cloud Shell の使用を開始する"^] 。
. 登録する `Microsoft.Compute/VMOrchestratorZonalMultiFD`次のコマンドを実行して機能を有効にします。
+
[]
====
az account set -s _<Azure サブスクリプション名または ID>_ az feature register --name VMOrchestratorZonalMultiFD --namespace Microsoft.Compute

====
. 登録ステータスと出力サンプルを確認します。
+
[]
====
az feature show -n VMOrchestratorZonalMultiFD --namespace Microsoft.Compute { "id": "/subscriptions/_<ID>_/providers/Microsoft.Features/providers/Microsoft.Compute/features/VMOrchestratorZonalMultiFD", "name": "Microsoft.Compute/VMOrchestratorZonalMultiFD", "properties": { "state": "登録済み" }, "type": "Microsoft.Features/providers/features" }

====

