---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, license conversion for node based, BlueXP, Console 
summary: 'ノードベースのライセンスの提供終了 (EOA) 後は、ライセンス変換ツールを使用して容量ベースのライセンスに移行する必要があります。' 
---
= Cloud Volumes ONTAPノードベースのライセンスを容量ベースのライセンスに変換する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノードベースのライセンスの提供終了 (EOA) 後は、 NetAppコンソールのライセンス変換ツールを使用して、容量ベースのライセンスに移行する必要があります。

年間契約または長期契約の場合、 NetAppでは、EOA 日 (2024 年 11 月 11 日) またはライセンスの有効期限の前にNetApp の担当者に連絡して、移行の前提条件が満たされていることを確認することをお勧めします。 Cloud Volumes ONTAPノードの長期契約がなく、オンデマンドの従量課金制 (PAYGO) サブスクリプションに対してシステムを実行している場合は、2024 年 12 月 31 日のサポート終了 (EOS) 前に変換を計画することが重要です。どちらの場合も、シームレスな移行を実現するために、 NetAppコンソールのライセンス変換ツールを使用する前に、システムが要件を満たしていることを確認する必要があります。

EOAとEOSの詳細については、以下を参照してください。link:concept-licensing.html#end-of-availability-of-node-based-licenses["ノードベースライセンスの提供終了"] 。

.タスク概要
* ライセンス変換ツールを使用すると、ノードベースのライセンス モデルから容量ベースのライセンス モデルへの移行がオンラインで実行されるため、データの移行や追加のクラウド リソースのプロビジョニングが不要になります。
* これは中断のない操作であり、サービスの中断やアプリケーションのダウンタイムは発生しません。
* Cloud Volumes ONTAPシステム内のアカウントとアプリケーション データはそのまま残ります。
* 変換後も、基盤となるクラウド リソースは影響を受けません。
* ライセンス変換ツールは、単一ノード、単一可用性ゾーン (AZ) での高可用性 (HA)、複数 AZ での HA、ライセンス持ち込み (BYOL)、PAYGO など、すべてのデプロイメント タイプをサポートします。
* このツールは、すべてのノードベースライセンスをソースとして、すべての容量ベースライセンスをターゲットとしてサポートしています。例えば、PAYGO Standardのノードベースライセンスをお持ちの場合、マーケットプレイスで購入した任意の容量ベースライセンスに変換できます。NetAppはBYOLライセンスの購入、延長、および更新を制限しています。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAPの BYOL ライセンスの利用制限"^] 。
* 変換は、すべてのクラウド プロバイダー (AWS、Azure、Google Cloud) でサポートされています。
* 変換後、ノードベースのライセンスのシリアル番号は、容量ベースの形式に置き換えられます。これは変換の一環として実行され、 NetAppサポート サイト (NSS) アカウントに反映されます。
* 容量ベースのモデルに移行すると、データは引き続きノードベースのライセンスと同じ場所に保持されます。このアプローチにより、データ配置の中断が保証されず、移行全体を通じてデータ主権の原則が維持されます。


.始める前に
* 顧客アクセスまたは管理者アクセスを持つ NSS アカウントが必要です。
* NSS アカウントは、コンソールにアクセスするために使用したユーザー資格情報で登録する必要があります。
* Cloud Volumes ONTAPシステムは、顧客アクセスまたは管理者アクセスを持つ NSS アカウントにリンクする必要があります。
* BYOL ライセンスまたはマーケットプレイス サブスクリプションのいずれか、有効な容量ベースのライセンスを用意する必要があります。
* 容量ベースのライセンスがアカウントで利用可能になります。このライセンスは、コンソールの *ライセンスとサブスクリプション* で利用できるマーケットプレイス サブスクリプションまたは BYOL/プライベート オファー パッケージになります。
* 宛先パッケージを選択する前に、次の基準を理解してください。
+
** アカウントに容量ベースの BYOL ライセンスがある場合、選択した宛先パッケージはアカウントの BYOL 容量ベース ライセンスと一致する必要があります。
+
*** いつ `Professional`を宛先パッケージとして選択する場合、アカウントには Professional パッケージの BYOL ライセンスが必要です。
*** いつ `Essentials`を宛先パッケージとして選択する場合、アカウントには Essentials パッケージの BYOL ライセンスが必要です。


** 宛先パッケージがアカウントの BYOL ライセンスの可用性と一致しない場合は、容量ベースのライセンスに選択したパッケージが含まれていない可能性があります。この場合、マーケットプレイスのサブスクリプションを通じて料金が請求されます。
** 容量ベースの BYOL ライセンスがなく、マーケットプレイス サブスクリプションのみがある場合は、選択したパッケージが容量ベースのマーケットプレイス サブスクリプションに含まれていることを確認する必要があります。
** 既存の容量ベースのライセンスに十分な容量がなく、追加の容量の使用に対して課金するマーケットプレイス サブスクリプションがある場合、マーケットプレイス サブスクリプションを通じて追加の容量に対して課金されます。
** 既存の容量ベースのライセンスに十分な容量がなく、追加の容量の使用に対して課金するマーケットプレイス サブスクリプションがない場合は、変換は実行できません。追加の容量を請求するか、現在のライセンスに利用可能な容量を拡張するには、マーケットプレイス サブスクリプションを追加する必要があります。
** 宛先パッケージがアカウントの BYOL ライセンスの可用性と一致しない場合、また既存の容量ベースのライセンスに十分な容量がない場合は、マーケットプレイスのサブスクリプションを通じて料金が請求されます。





NOTE: これらの要件のいずれかが満たされていない場合、ライセンスの変換は行われません。特定のケースでは、ライセンスは変換される可能性がありますが、使用することはできません。情報アイコンをクリックして問題を特定し、修正措置を講じます。

.手順
. *システム* ページで、ライセンスの種類を変更するシステムの名前をダブルクリックします。
. [概要] タブで、[機能] パネルをクリックします。
. *充電方法*の横にある鉛筆アイコンを確認してください。システムの充電方法が `Node Based`容量課金に変更することができます。
+

TIP: Cloud Volumes ONTAPシステムがすでに容量によって課金されている場合、またはいずれかの要件が満たされていない場合、アイコンは無効になります。

. *ノードベースのライセンスを容量ベースに変換する*画面で、システム名とソース ライセンスの詳細を確認します。
. 既存のライセンスを変換するための宛先パッケージを選択します。
+
** 必需品。デフォルト値は `Essentials`。
** プロ


. BYOL ライセンスをお持ちの場合は、変換が完了した後にコンソールからノードベースのライセンスを削除するチェックボックスを選択できます。変換がまだ進行中の場合は、このチェックボックスを選択してもコンソールからライセンスは削除されません。このオプションはマーケットプレイスのサブスクリプションでは使用できません。
. 変更の影響を理解していることを確認するためにチェックボックスを選択し、「続行」をクリックします。


.終了後の操作
新しいライセンスのシリアル番号を表示し、コンソールの *ライセンスとサブスクリプション* メニューで変更を確認します。



== さまざまなハイパースカラーの価格設定

価格の詳細については、 https://bluexp.netapp.com/pricing/["NetAppコンソールのウェブサイト"^] 。

特定のハイパースカラーのプライベートオファーに関する情報については、下記までお問い合わせください。

* AWS - awspo@netapp.com
* Azure - azurepo@netapp.com
* Google Cloud - gcppo@netapp.com

