---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: AWS に Cloud Volumes ONTAP をデプロイするための前提条件が完了していることを確認してください。 
---
= AWS での Cloud Volumes ONTAP の導入概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP をデプロイするには、まず AWS サブスクリプションと Cloud Volumes ONTAP ライセンスについて理解しておく必要があります。また、AWS アカウント用に NetApp Console エージェントが作成されていることを確認する必要があります。このトピックの情報の多くは、Cloud Volumes ONTAP のデプロイを開始する前に、Console のセットアップの一部として実行する必要があります。

[cols="20,35,25,25"]
|===
| Task | 説明 | 参照 | プライベートモード展開に関する注意事項 


 a| 
コンソールエージェントを作成する
 a| 
コンソールエージェントがまだない場合は、Cloud Volumes ONTAP をデプロイする前に作成してください。インターネットアクセスのないサブネットにデプロイする場合は、コンソールエージェントを手動でインストールし、そのエージェント上で実行されている NetApp Console にアクセスしてください。
 a| 
コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["AWSでコンソールエージェントを作成する"^]
 a| 
インターネットアクセスのないサブネットにデプロイする場合は、コンソールエージェントを手動でインストールし、そのコンソールエージェント上で動作している NetApp Console ユーザーインターフェースにアクセスしてください。コンソール設定ガイドを参照してください：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["インターネット接続なしでコンソールエージェントを手動でインストールする"^]



 a| 
構成を計画する
 a| 
コンソールでは、ワークロード要件に一致する事前構成済みのパッケージが提供されており、独自の構成を作成することもできます。独自の構成を選択する場合は、利用可能なオプションを理解する必要があります。
 a| 
link:task-planning-your-config.html["構成を計画する"]
 a| 
プライベート環境での展開についても、同様の計画上の考慮事項が必要です。



 a| 
ネットワークを設定する
 a| 
. VPC とサブネットが Console エージェントと Cloud Volumes ONTAP 間の接続をサポートしていることを確認してください。
. AutoSupport のアウトバウンドインターネットアクセスを有効にします。
. データ階層化のためにAmazon S3へのVPCエンドポイントを設定します。Cloud Volumes ONTAPからコールドデータを低コストのオブジェクトストレージに階層化する場合は、VPCエンドポイントが必要です。

 a| 
link:reference-networking-aws.html["AWSのネットワーク要件"]
 a| 
AutoSupport のアウトバウンドインターネットアクセスは必須ではありません。その他のネットワーク要件はすべて変更ありません。



 a| 
AWS KMSを設定する
 a| 
Amazon の暗号化を Cloud Volumes ONTAP で使用する場合は、有効な Customer Master Key （CMK）が存在することを確認し、キーポリシーを変更して、Console エージェントの IAM ロールをキーユーザーとして追加してください。
 a| 
link:task-setting-up-kms.html["AWS KMSを設定する"]
 a| 
プライベート環境での展開にも同様の手順が適用されます。



 a| 
コンソールから Cloud Volumes ONTAP を導入する
 a| 
前提条件をすべて満たしたら、ウィザードの手順に従って AWS に Cloud Volumes ONTAP をデプロイする手順を完了できます。
 a| 
* link:task-quick-deploy-aws.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-otc-aws.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]

 a| 
デプロイを開始する前に、NetApp から Cloud Volumes ONTAP ライセンスを購入済みであることを確認してください。プライベート環境のデプロイには、ノードベースの BYOL ライセンスが必要です。Marketplace サブスクリプションは、Cloud Volumes ONTAP の使用料金の請求には対応していません。ライセンスファイルを NetApp から入手し、デプロイ時にアップロードしてください。参照：

* link:concept-license-management.html["ノードベースBYOLのライセンス管理"]
* link:task-manage-node-licenses.html["ノードベースのBYOLライセンスを管理する"]
* link:task-quick-deploy-aws.html["クイック作成でCloud Volumes ONTAPを導入する"]
* link:task-deploying-otc-aws.html["詳細オプションを使用して Cloud Volumes ONTAP を導入する"]


|===
.関連リンク
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["AWS のコンソールエージェントを作成する"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["AWS Marketplaceからコンソールエージェントを作成する"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["オンプレミスでコンソールエージェントをインストールしてセットアップする"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["コンソールエージェントのAWS権限"^]

