= Azure の Premium SSD v2 ディスクのパフォーマンスを向上させる機能
:allow-uri-read: 




[[ability-to-enhance-performance-of-premium-ssd-v2-disks-in-azure]]
=== Azure の Premium SSD v2 ディスクのパフォーマンスを向上させる機能

IOPS およびスループット パラメーターを変更することで、Azure の Premium SSD v2 マネージド ディスクのパフォーマンスを向上できるようになりました。この機能を使用すると、ワークロード要件に基づいてシステムのストレージ パフォーマンスを最適化できます。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-perf-params-azure.html["Azure のCloud Volumes ONTAPの Premium SSD v2 ディスク パフォーマンスを管理する"^]。



[[overage-charging-for-essentials-licenses-simplified]]
=== Essentialsライセンスの超過料金の簡素化

Cloud Volumes ONTAPマーケットプレイスの年間契約／プライベートオファーにおけるEssentialsライセンスの超過料金の計算方法は、Bring-Your-Own License（BYOL）パッケージと整合されるようになりました。以前は、超過料金は、対象のEssentialsパッケージに対して時間単位のマーケットプレイスレートで請求されていました。マーケットプレイスの年間契約に複数のEssentialsパッケージが含まれている場合、NetApp Consoleは、お客様の契約に含まれるより高額なEssentialsパッケージの利用可能容量に対して、Essentialsパッケージの超過料金を請求します。これにより、Essentialsパッケージの超過料金計算が簡素化され、BYOLライセンスからサブスクリプションベースのモデルへのスムーズな移行が実現されます。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Essentialsライセンスの超過料金の請求方法"^]



[[support-for-azure-edsv6-sizes-series]]
=== Azure Edsv6 サイズ シリーズのサポート

Cloud Volumes ONTAP 9.17.1 以降では、新しいCloud Volumes ONTAPインスタンス用に、 NetApp Consoleを通じて Azure Edsv6 シリーズ VM をデプロイできます。 Cloud Volumes ONTAP 9.17.1 以降では、新しいデプロイメントでは第 2 世代 VM のみがサポートされます。これらの第 2 世代マシンは、Unified Extensible Firmware Interface (UEFI)、Azure Boost システム、NVMe などの最新テクノロジと互換性があります。これらは、データベース サーバーや分析エンジンなど、高速なローカル ストレージを必要とするメモリを大量に消費するシステムやアプリケーションに最適です。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Azure でサポートされるCloud Volumes ONTAPの構成"^]
