= Cloud Volumes ONTAPの次世代Google Cloud VMのサポート
:allow-uri-read: 




[[cloud-volumes-ontap-support-for-next-generation-google-cloud-vms]]
=== Cloud Volumes ONTAPの次世代Google Cloud VMのサポート

9.18.1では、NetAppが新しいCloud Volumes ONTAPのデプロイメントをN2 VMから次世代Google Cloud C3シリーズVMへ移行し、より高速でスケーラブルなエクスペリエンスを提供します。Google CloudでCloud Volumes ONTAP 9.18.1以降をデプロイする際に、C3シリーズVMを活用できるようになりました。C3シリーズのマシンは、Google Virtual NIC（gVNIC）とHyperdisk Balancedディスクを使用することで、パフォーマンスの向上と容量制限の拡大を実現し、負荷の高いワークロードに対してダイナミックなパフォーマンスを確保します。


NOTE: 今のところ、Cloud Volumes ONTAP は単一ノード展開でのみ C3 シリーズをサポートしています。

Cloud Volumes ONTAPシステムが9.18.1以降を実行している場合、簡単なシングルノード展開に使用する事前設定済みパッケージは自動的にC3 VMを使用し、ワークロードのニーズに基づいてIOPSおよびスループットパラメータをカスタマイズできるようになります。同様に、アグリゲートを作成する際に、Hyperdisk Balancedディスクを追加して、Google Cloudでのパフォーマンスとスケーラビリティを向上させることができます。さらに、デフォルトのFlash Cacheサポート用にC3シリーズマシンのLSSDバリアントを選択することもできます。

C3 は Hyperdisk Balanced ディスクのみをサポートしているため、アグリゲートにボリュームを追加するときに C3 VM のディスクタイプを変更することはできません。同様に、N2 VM タイプのシステムを C3 VM に複製する場合、ディスクタイプはデフォルトで Hyperdisk Balanced に設定されます。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google CloudでサポートされているCloud Volumes ONTAPの構成"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google ドキュメント：C3 マシンシリーズ"^]



[[vnet-security-for-cloud-volumes-ontap-in-azure]]
=== AzureのCloud Volumes ONTAPのVNetセキュリティ

Cloud Volumes ONTAP 9.18.1以降のAzure単一および複数の可用性ゾーンでの導入では、転送中のデータを保護するための多層セキュリティ戦略の一部として、Azure Virtual Network（VNet）暗号化をサポートしています。Cloud Volumes ONTAPは、AzureのネイティブなDatagram Transport Layer Security（DTLS）プロトコルを活用して、ONTAPノード、管理インターフェイス、およびその他のAzureサービス間の通信を保護し、傍受や不正アクセスを防止します。このネットワークレベルの暗号化は、ONTAPの組み込みストレージおよび保存データ保護機能を補完し、データのエンドツーエンドのセキュリティを提供します。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html#networking-for-azure-vnet-encryption["Azure VNet 暗号化のネットワーク"]
